<?php
/**
 * Mageplace Facebook Connect
 *
 * @category    Mageplace_Facebook
 * @package     Mageplace_Facebook_Connect
 * @copyright   Copyright (c) 2011 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */

// WARNING! Don't change span class "facebookconnect-button"
?>
<span class="facebookconnect-button">
<?php if(strtolower(substr($this->getLinkUrl(),0,4))==='http'): ?>
	<a href="<?php echo $this->getLinkUrl(); ?>" title="<?php echo $this->getTitle(); ?>" class="link-facebook">
<?php elseif($this->getLinkUrl()): ?>
	<a href="<?php echo $this->getUrl($this->getLinkUrl()); ?>" title="<?php echo $this->getTitle(); ?>" class="link-facebook">
<?php endif; ?>
		<span><?php echo $this->getTitle(); ?></span>
<?php if($this->getLinkUrl()): ?>
	</a>
<?php endif ?>
</span>