<table class="tab-deal">
	<tr>
		<td>
			<a href="<?php echo $this->getUrl('').'daily-deals'?>">
				<span><span><?php echo $this->__('Active Deals');?></span></span>
			</a>
		</td>
		<td class="active">
			<a href="<?php echo $this->getUrl('').'daily-deals/past'?>">
				<span><span><?php echo $this->__('Past Deals');?></span></span>
			</a>
		</td>
		<td>
			<a href="<?php echo $this->getUrl('').'daily-deals/comming'?>">
				<span><span><?php echo $this->__('Comming Deals');?></span></span>
			</a>
		</td>
	</tr>
</table>

<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_pastdealsCollection=$this->getPastdeals();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_pastdealsCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_pastdealsCollection as $_pastdeal): ?>
    <?php 
    	$soldqty = $_pastdeal->getSoldQty();
    $_product = Mage::getModel('catalog/product')->load($_pastdeal->getProductId());?>
        <li class="item<?php if( ++$_iterator == sizeof($_pastdealsCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php //echo $this->getPriceHtml($_product, true) ?>
                    <?php 
                		$_coreHelper = $this->helper('core');
                		$_taxHelper = $this->helper('tax');
					$_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice(), $_simplePricesTax);     
                	$_finalPrice = $_pastdeal->getDailydealPrice(); 
                ?>        
                <p class="old-price" >Regular Price:
					<span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>-related">
						   <span class="price"><?php echo $_coreHelper->currency($_regularPrice,true,false) ?></span>
					</span>
				</p>        
                <p class="special-price">
	                <span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
	                    Special Price: <?php echo $_coreHelper->currency($_finalPrice,true,false) ?>
	                </span>
	            </p>      
	            
 				<div>
				<?php if ($soldqty > 1 || $soldqty == 0){?>
 				<?php echo $this->__('There are')?><span style="color: red; font-size: 12px; font-weight: bold;">&nbsp;<?php echo $soldqty;?> items</span>&nbsp;solved. 				
	            <?php }elseif ($soldqty == 1){?>
	            <span style="color: red; font-size: 12px; font-weight: bold;">An item</span> has solved.
	            <?php } ?>	            
	            </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php 
    	$_collectionSize = $_pastdealsCollection->count(); 
     	$columncount = Mage::getStoreConfig('dailydeal/general/columncount');//echo $columncount;die;
    	$_columnCount = $columncount?$columncount:3;//$this->getColumnCount(); 
    	//echo $_columnCount;die;
    ?>
    <?php $i=0; foreach ($_pastdealsCollection as $_pastdeal): ?>
    <?php 			
        	$soldqty = $_pastdeal->getSoldQty();
    
    $_product = Mage::getModel('catalog/product')->load($_pastdeal->getProductId());
    ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" style="height: 215px;">
               <div> <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php //echo $this->getPriceHtml($_product, true) ?>
                <?php 
                		$_coreHelper = $this->helper('core');
                		$_taxHelper = $this->helper('tax');
					$_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice(), $_simplePricesTax);     
                	$_finalPrice = $_pastdeal->getDailydealPrice(); 
                ?>        
                <p class="old-price" >Regular Price:
					<span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>-related">
						   <span class="price"><?php echo $_coreHelper->currency($_regularPrice,true,false) ?></span>
					</span>
				</p>        
                <p class="special-price">
	                <span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
	                    Special Price: <br/><?php echo $_coreHelper->currency($_finalPrice,true,false) ?>
	                </span>
	            </p></div>
     
 				<div>
				<?php if ($soldqty > 1 || $soldqty == 0){?>
 				<?php echo $this->__('There are')?><span style="color: red; font-size: 12px; font-weight: bold;">&nbsp;<?php echo $soldqty;?> items</span>&nbsp;solved 				
	            <?php }elseif ($soldqty == 1){?>
	            <span style="color: red; font-size: 12px; font-weight: bold;">An item</span> has solved.
	            <?php } ?>	            
	            </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
