<div style="  background: none repeat scroll 0 0 #999999; border: 0 none; padding: 3px 10px;color:white;font-weight:bold;font-size:14px;padding:5px;font-family:verdana;text-align:center;">
    Search
</div>
<script type="text/javascript">
    function searchproducts()
    {
        var text = document.getElementById('searchname').value;
        var url = document.getElementById('defaulturl').value;
        document.getElementById('searchform').action = url + text;

        if(text.trim() == '') {
            return false;
        } else {
            return true;
        }
    }
</script>
<form method="post" action="" name="searchform" id="searchform">
    <div style="padding-top:10px;">
        <ul class="form-list">
            <li class="fields" style="">
                <div class="field name">
                    <div class="input-box" style="width:230px;">
                        <input style="width:180px;" type="text" class="input-text required-entry" title="search Name"
                               value="" name="searchname" id="searchname"/>
                        <input type="hidden" value="<?php echo $this->getUrl('embeded/search/q') ?>" name="defaulturl" id="defaulturl"/>
                        <button title="Search" class="leftsearch"
                                style="background-color:#999999;border:none;float:right;padding:3px;width:25px;"
                                type="image" onclick="return searchproducts();">
                                    <span> <span> <img src="<?php echo $this->getSkinUrl('images/search.png') ?>"/> </span> </span>
                        </button>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</form>
<div
    style="  background: none repeat scroll 0 0 #999999; border: 0 none; padding: 3px 10px;color:white;font-weight:bold;font-size:14px;padding:5px;font-family:verdana;text-align:center;">
    durchsuchen By Category
</div>
<div>
    <?php
        $options = Mage::helper('embeded')->getVideoCategoryOptions();
        foreach ($options as $optiondata): ?>
            <div class="embed"
                 style="border-bottom: 1px solid #DDDDDD;display: block;padding: 3px 0;text-decoration: none !important;">
                <?php if ($optiondata['value'] == $this->getRequest()->getParam('search')) : ?>
                    <a style="font-weight:bold;color: #9E0B0F !important;text-decoration:none;"
                       href="<?php echo $this->getUrl('embeded/category/q') . $optiondata['value'] ?>"> <?php echo $optiondata['label']; ?></a>
                <?php else: ?>
                <a class="anchor" style="color: #5F5D5C;text-decoration:none;"
                       href="<?php echo $this->getUrl('embeded/category/q') . $optiondata['value'] ?>"> <?php echo $optiondata['label']; ?></a>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
</div>
<div style="  background: none repeat scroll 0 0 #999999; border: 0 none; padding: 3px 10px;color:white;font-weight:bold;font-size:14px;padding:5px;font-family:verdana;text-align:center;">
    Similar Products
</div>
<div>
    <?php
        $relatedProductIds = $this->getSimilarProducts();
        foreach ($relatedProductIds as $relatedProductId)
        {
            $relatedProduct = Mage::getModel('catalog/product')->load($relatedProductId);
            $relatedProducturl = $relatedProduct->getProductUrl() . "?" . Mage::getSingleton('core/session')->getAffilicateUrl();
    ?>
        <li class="" style="list-style:none;background:#F0F0F0;padding:5px;margin-bottom:10px;">

            <div style="">
                <a style="width:120px;" class="" title="" href="<?php echo $relatedProducturl; ?>">
                    <img width="100" height="100" alt="" src="<?php echo $relatedProduct->getImageUrl(); ?>"/>
                </a>

                <div style="float:right;padding-top:45px;width:105px;">
                    <a href="<?php echo $relatedProducturl; ?>"
                       style="font-size: 14px;"><?php echo $relatedProduct->getName(); ?></a>
                </div>
            </div>
        </li>
    <?php } //foreach ($relatedProductsId as $relatedProductId)?>
</div>