<div style="float:left;width:1000px;">
    <h1 class="logo">
        <?php $_logoAlt = Mage::getStoreConfig('design/header/logo_alt'); ?>
        <a href="<?php echo $this->getUrl('') ?>?<?php echo Mage::getSingleton('core/session')->getAffilicateUrl() ?>" title="<?php echo $_logoAlt ?>" class="logo">
            <img src="<?php echo $this->getSkinUrl(Mage::getStoreConfig('design/header/logo_src')); ?>" alt="<?php echo $_logoAlt ?>"/>
        </a>
    </h1>
    <div style="clear: both"></div>
    <div style="float:left;width:745px;">
        <?php echo $this->getChildHtml('embeded-products-lists') ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    </div>
    <div style="float:right;width:230px;">
        <?php echo $this->getChildHtml('embeded-right-col') ?>
    </div>
</div>
