<?php
$_helper = $this->helper('catalog/output');
$dataid=Mage::getSingleton('core/session')->getCodevalue($data);
$purl=$this->allquery();
$resource = Mage::getSingleton('core/resource');
$connection= $resource->getConnection('core_read');			
$query="select * from tbl_embedcode where embed_code='$dataid'";
$result=$connection->query($query);
$alldata = $result->fetch(); 
$prourl= $alldata['join_id'];
$prodIdss=explode(',',$purl['product_id']);  
array_pop($prodIdss);
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php 
$collection = $this->getCollection();
$productIds=array();
foreach($collection as $_product)
{
    $productIds[]=$_product->getId();
}
?>
<?php 
/*
 * RECENT PRODUCTS
 */
?>

<?php
$_productCollection = Mage::getResourceModel('reports/product_collection')
                   ->addAttributeToSelect('*')
                    ->setVisibility(array(2,3,4))                   
                    ->setOrder('created_at', 'desc');
$rcount=0;
foreach ($_productCollection as $pro)
{
  if($rcount<6)
      {
        $recentproduct[]= $pro->getId();  
        $rcount++;
      }
}
?>
<?php 
/*
 * POPULAR PRODUCTS
 */
$productCount=6;
$productss = Mage::getResourceModel('reports/product_collection')
                                                    ->addAttributeToSelect('*')     
                                                    ->addOrderedQty()
                                                    ->setStoreId($storeId)
                                                    ->addStoreFilter($storeId)                  
                                                    ->setOrder('ordered_qty', 'desc');                                                  
$pcount=0;
foreach ($productss as $poppro) 
{
  if($pcount<6)
    {
        $popularproduct[]= $poppro->getId();  
        $pcount++;
    }
}
?>
 <?php 
        if($this->getRequest()->getParam('searchdata')) 
        { 
            $textdata= $this->getRequest()->getParam('searchdata'); 
        }
        else
        {
             $attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_product', 'video_category ');
                if ($attribute->usesSource()):
                    $options = $attribute->getSource()->getAllOptions(false);
                endif;
                foreach($options as $optiondata): 
                    if($optiondata['value']==$this->getRequest()->getParam('search')) {
                        $textdata= $optiondata['label'];
                    } 
           endforeach; 
        } 
?>
<?php 
/*
 * TOP RATED PRODUCTS
 * 
 */
$_productCollection1 = Mage::getResourceModel('reports/product_collection')
                     ->addAttributeToSelect('*')
                     ->setVisibility(array(2,3,4));
$_productCollection1->joinField('rating_summary', 'review/review_aggregate', 'rating_summary', 'entity_pk_value=entity_id',  array('entity_type' => 1, 'store_id' => Mage::app()->getStore()->getId()), 'left');                
$_productCollection1->setOrder('rating_summary', 'desc');
$tcount=0;
foreach ($_productCollection1 as $toppro)
{
      if($tcount<6)
      {
        $topratedproduct[]= $toppro->getId();  
        $tcount++;
      }
}
?>
<?php $code = $this->getRequest()->getParam('code'); ?>
<?php if($collection->getSize()): ?>

<?php /********* Grid Mode ************/ ?>
<div style="float:left;width:1000px;">
    <div style="float:left;width:735px;">
         <div class="listgrid1">
             <ul class="products-grid" style="width:735px;">
 <?php 
    $_collectionSize = $collection->count();
    $_columnCount = $this->getColumnCount();
    if(!$_columnCount){ $_columnCount = 3; } 
    $i=0;
    $recentcount=0;
    $popcount=0;
    $searchcount=0;
    $topcount=0;
    $raw=array();
    foreach ($prodIdss as $key=>$value):
        $free= explode('-',$value);
        $prodid=$free[0];
        $identifier=$free[1];
        $category = Mage::getModel('catalog/product')->load($prodid);
        $ProductUrl=$category->getProductUrl()."/?".$prourl;
        $Id= $category->getId();
        $_myprodsamples = Mage::getModel('downloadable/link')->getCollection()->addProductToFilter($Id);
        $products = Mage::getModel('catalog/product')->load($Id);
        $type=$products['type_id'];
        $ustreamvideo=$products['ustream_video'];
        $productmaterial=$products['product_material'];
        $curencySymbol =  Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
            foreach($_myprodsamples as $_sample){
                $video= $_sample['sample_url'];
                $video1= $_sample['link_url'];
                }
                $vdata=explode("v=",$video);
?>
 <?php if ($i++%$_columnCount==0): ?>
 <?php endif ?>
                           
 <?php /*****************************************************RECENT PRODUCTS ***************************************************/ ?>
        
 <?php  if($code != Null ) { if (in_array($prodid, $recentproduct) && $identifier=='R') {
            if($recentcount==0 ) { ?>
                <div class="recent_courses_bg" style="margin-bottom:10px;">
                         <div class="recent_courses_left">
                            RECENT COURSES
                         </div>
                </div>
           <?php $recentcount++; } ?>
                <li style="float:left;" class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
           <?php } ?>   
<?php /*****************************************************POPULAR PRODUCTS ***************************************************/ ?>      
                    
 <?php if (in_array($prodid, $popularproduct) && $identifier== 'P') {  
           if($popcount==0 ) { ?>
                 <div class="recent_courses_bg" style="margin-bottom:10px;">
                         <div class="recent_courses_left">
                            POPULAR COURSES 
                         </div>
                </div>
           <?php $popcount++; } ?>
                <li style="float:left;" class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
           <?php } ?> 
 <?php /*****************************************************TOP RATED PRODUCTS ***************************************************/ ?>  
        <?php if($identifier=='T') { 
               if($topcount==0 ) {?>
                       <div class="recent_courses_bg" style="margin-bottom:10px;">
                             <div class="recent_courses_left">
                                TOP RATED COURSES
                             </div>
                       </div>
                <?php $topcount++; } ?>
                        <li  style="float:left;" class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <?php } ?>
                            
                    <?php if($vdata['1']!=NULL && $type=='downloadable'&& $productmaterial=='7'): ?>
                             <div class="videosclick3" onclick="thevid=document.getElementById('thevideo<?php echo $countdata ?>'); thevid.style.display='block';document.getElementById('viewplayer2<?php echo $countdata ?>').src = document.getElementById('viewplayer2<?php echo $countdata ?>').src.replace('autoplay=0','autoplay=1'); this.style.display='none'">
                                 <?php if($products->getImageUrl() !=NULL && $products['image']!='no_selection'){ ?>
                                      <img style="margin:15px;padding-left:5px;" src="<?php echo $this->helper('catalog/image')->init($products, 'small_image')->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize(195,180) ?>"  style="cursor:pointer" />
                                 <?php } else { ?>
                                      <img style="margin:15px;padding-left:5px;" src="http://img.youtube.com/vi/<?php echo $vdata['1']?>/2.jpg"  width="195" height="180" style="cursor:pointer" />
                                 <?php  }  ?>
                                  <a style="left:95px;" href="javascript:void(0)" ></a>
                             </div>
                              <div id="thevideo<?php echo $countdata ?>" style="display:none"> 
                                    <?php   echo  '<iframe id="viewplayer2'.$countdata.'" style="margin:15px;padding-left:5px;" title="YouTube video player" class="youtube-player" type="text/html" width="195" height="180"  src="https://www.youtube.com/embed/'.$vdata['1'].'?autoplay=0" frameborder="0" allowFullScreen></iframe>'; ?>
                              </div>
                            
                   <?php elseif($productmaterial==8 && $video1!=NULL ): ?>
                             <script type="text/javascript" src="<?php echo $this->getSkinUrl('jwplayer/jwplayer.js'); ?>"></script>
                             <script type="text/javascript" src="<?php echo $this->getSkinUrl('jwplayer/jwplayer.html5.js'); ?>"></script>
                              <?php 
                                      if($products['image'] !='no_selection')
                                      {
                                           $img=$this->helper('catalog/image')->init($products, 'image')->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize(290,190);
                                      }
                                      else if($products['image'] =='no_selection')
                                      {
                                           $img=$this->getSkinUrl('images/poster.jpg');
                                      }
                               ?>
                                             <div style="padding:15px !important;">
                                <div id="myElementlist<?php echo $countdata ?>" class="jwwrap" class="listgrid">Loading the player...</div>
                             </div>
                            <script type="text/javascript">
                                    jwplayer("myElementlist<?php echo $countdata ?>").setup({
                                        image:'<?php echo $img ?>',
                                        'width': '195',
                                       'height': '180',
                                    flashplayer : '<?php echo $this->getSkinUrl('jwplayer/jwplayer.flash.swf'); ?>',
                                    file: "<?php echo $video1 ?>"
                                  });
                            </script>
                 <?php  else: ?>
                             <div>
                                <a href="<?php echo $ProductUrl ?>" title="<?php echo $this->stripTags($this->getImageLabel($products, 'small_image'), null, true) ?>" class="product-image">
                                    <img src="<?php echo $this->helper('catalog/image')->init($products, 'small_image')->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize(195,180) ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($products, 'small_image'), null, true) ?>" />
                                </a> 
                             </div>
                 <?php endif; ?>
                  <h2 class="product-name"><a href="<?php echo $ProductUrl; ?>" target="_blank"  title="<?php echo $category->getUrl() ?>"><?php echo $category->getName() ?></a></h2>
                           <div class="price-box">
                                <span id="product-price-150" class="regular-price">
                                     <span class="price"><?php  
                                            echo $curencySymbol.number_format( $category->getPrice(),2);?>
                                     </span>                                   
                                 </span>
                            </div>
                            <div class="actions">
                                 <?php if($products['is_salable']): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php  echo $ProductUrl ?>')"><span><span><?php echo $this->__('BUY NOW') ?></span></span></button>
                                <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                            </div>
               </li>
      <?php } ?>
<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
<?php endif ?>
<?php endforeach; ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        
<?php /*********************************************** SEARCH PRODUCTS *********************************************************/ ?>
<?php if($this->getRequest()->getParam('search')!=NULL || $this->getRequest()->getParam('searchdata')!=NULL ) {     
       foreach ($collection as $_product){
            $category = Mage::getModel('catalog/product')->load($_product->getId());
            $ProductUrl=$category->getProductUrl()."/?".$prourl;
            $Id= $category->getId();
            $_myprodsamples = Mage::getModel('downloadable/link')->getCollection()->addProductToFilter($Id);
            $products = Mage::getModel('catalog/product')->load($Id);
            $type=$products['type_id'];
            $ustreamvideo=$products['ustream_video'];
            $productmaterial=$products['product_material'];
            $curencySymbol =  Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
            foreach($_myprodsamples as $_sample){
                 $video= $_sample['sample_url'];
                 $video1= $_sample['link_url'];
            }
            $vdata=explode("v=",$video);
  ?>
        <?php if ($i++%$_columnCount==0): ?>
         <?php endif ?> 
             <?php if($searchcount==0 ) {?>
                 <div class="recent_courses_bg" style="margin-bottom:10px;">
                         <div class="recent_courses_left">
                              Search Results For "<?php echo $textdata; ?>"
                          </div>
                </div>
                <?php $searchcount++; } ?>
          <li style="float:left;" class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
              <?php if($vdata['1']!=NULL && $type=='downloadable'&& $productmaterial=='7'): ?>
                      <div class="videosclick3" onclick="thevid=document.getElementById('thevideo<?php echo $countdata ?>'); thevid.style.display='block';document.getElementById('viewplayer2<?php echo $countdata ?>').src = document.getElementById('viewplayer2<?php echo $countdata ?>').src.replace('autoplay=0','autoplay=1'); this.style.display='none'">
                         <?php if($products->getImageUrl() !=NULL && $products['image']!='no_selection'){ ?>
                              <img style="margin:15px;padding-left:5px;" src="<?php echo $this->helper('catalog/image')->init($products, 'small_image')->resize(195,180) ?>"  style="cursor:pointer" />
                         <?php } else { ?>
                              <img style="margin:15px;padding-left:5px;" src="http://img.youtube.com/vi/<?php echo $vdata['1']?>/2.jpg"  width="195" height="180" style="cursor:pointer" />
                         <?php  }  ?>
                          <a style="left:95px;" href="javascript:void(0)" ></a>
                      </div>
                      <div id="thevideo<?php echo $countdata ?>" style="display:none"> 
                            <?php   echo  '<iframe id="viewplayer2'.$countdata.'" style="margin:15px;padding-left:5px;" title="YouTube video player" class="youtube-player" type="text/html" width="195" height="180"  src="https://www.youtube.com/embed/'.$vdata['1'].'?autoplay=0" frameborder="0" allowFullScreen></iframe>'; ?>
                      </div>
                            
              <?php elseif($productmaterial==8 && $video1!=NULL ): ?>
                     <script type="text/javascript" src="<?php echo $this->getSkinUrl('jwplayer/jwplayer.js'); ?>"></script>
                     <script type="text/javascript" src="<?php echo $this->getSkinUrl('jwplayer/jwplayer.html5.js'); ?>"></script>
                     <div style="padding:15px !important;">
                     <div id="myElementlist<?php echo $countdata ?>" class="jwwrap" class="listgrid">Loading the player...</div></div>

                     <script type="text/javascript">
                            jwplayer("myElementlist<?php echo $countdata ?>").setup({
                                'width': '195',
                               'height': '180',
                            flashplayer : '<?php echo $this->getSkinUrl('jwplayer/jwplayer.flash.swf'); ?>',
                            file: "<?php echo $video1 ?>"
                          });
                    </script>
             <?php  else: ?>
                     <div>
                        <a href="<?php echo $ProductUrl ?>" title="<?php echo $this->stripTags($this->getImageLabel($products, 'small_image'), null, true) ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($products, 'small_image') ?>" width="195" height="180" alt="<?php echo $this->stripTags($this->getImageLabel($products, 'small_image'), null, true) ?>" />
                        </a> 
                    </div>
             <?php endif; ?>

                 <h2 class="product-name"><a href="<?php echo $ProductUrl; ?>" target="_blank"  title="<?php echo $category->getUrl() ?>"><?php echo $category->getName() ?></a></h2>
                    <div class="price-box">
                         <span id="product-price-150" class="regular-price">
                              <span class="price"><?php  
                                   echo $curencySymbol.number_format( $category->getPrice(),2);?>
                               </span>                                   
                          </span>
                    </div>
                    <div class="actions">
                         <?php  ?>
                        <?php if($products['is_salable']): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $ProductUrl ?>')"><span><span><?php echo $this->__('BUY NOW') ?></span></span></button>
                        <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                   </div>
          </li>
 <?php  }  } ?>
       </ul>
   </div>
 </div>
<?php endif; ?>
<?php if (count($collection)==0) { ?>
    <div style="float:left;width:1000px;">
        <div style="border:1px solid #9E0B0F;padding:5px;width:735px;float:left;font-size:14px;">
            <?php echo 'There is no result found for "'.$textdata.'"'; ?>
        </div>
<?php } ?>
         
  
<div style="float:right;width:230px;">
    <div style="  background: none repeat scroll 0 0 #999999; border: 0 none; padding: 3px 10px;color:white;font-weight:bold;font-size:14px;padding:5px;font-family:verdana;text-align:center;">
        Search
    </div>
    <form method="post" action="" name="searchform" id="searchform">
    <div style="padding-top:10px;">
           <ul class="form-list">
                <li class="fields" style="">
                      <div class="field name">
                           <div class="input-box" style="width:230px;">
                               <input style="width:193px;" type="text" class="input-text required-entry" title="search Name" value="" name="searchname" id="searchname"/>
                               <input style="width:218px;" type="hidden" class="input-text required-entry" title="search Name" value="<?php echo Mage::getBaseUrl().'embeded/index/searchdata/' ?>" name="defaulturl" id="defaulturl"/>
                            <button title="Search" class="leftsearch" style="background-color:#999999;border:none;float:right;padding:3px;width:25px;" type="image" onclick="searchproducts();">
                                <span>
                                    <span>
                                        <img src="<?php echo $this->getSkinUrl('images/search.png') ?>"/>
                                    </span>
                                </span>
                            </button>
                             <!--  <button style="background:#FFFFFF;margin-bottom:5px;padding:3px;" type="submit" title="<?php echo $this->__('GO') ?>" class="button btn-cart" "><span><span><?php echo $this->__('GO') ?></span></span></button>
                           -->
                           </div>
                        </div>
                 </li>
             </ul>
    </div>
    </form>
     <div style="  background: none repeat scroll 0 0 #999999; border: 0 none; padding: 3px 10px;color:white;font-weight:bold;font-size:14px;padding:5px;font-family:verdana;text-align:center;">
       durchsuchen By Category
    </div>
    <div>
    <?php $attribute = Mage::getSingleton('eav/config')->getAttribute('catalog_product', 'video_category ');
                                            if ($attribute->usesSource()):
                                                $options = $attribute->getSource()->getAllOptions(false);
                                            endif;
                                            foreach($options as $optiondata): ?>
                                                 <div class="embed" style="border-bottom: 1px solid #DDDDDD;display: block;padding: 3px 0;text-decoration: none !important;">
                                                     <?php if($optiondata['value']==$this->getRequest()->getParam('search')) {?>
                                                     <a style="font-weight:bold;color: #9E0B0F !important;text-decoration:none;" href="<?php echo Mage::getBaseUrl().'embeded/index/search/'.$optiondata['value']?>"> <?php echo $optiondata['label']; ?></a>
                                                     <?php } else {?>
                                                      <a  class="anchor" style="color: #5F5D5C;text-decoration:none;" href="<?php echo Mage::getBaseUrl().'embeded/index/search/'.$optiondata['value']?>"> <?php echo $optiondata['label']; ?></a>
                                                     <?php } ?>
                                                 </div>
                                <?php endforeach; ?>
    </div>   
    <div style="  background: none repeat scroll 0 0 #999999; border: 0 none; padding: 3px 10px;color:white;font-weight:bold;font-size:14px;padding:5px;font-family:verdana;text-align:center;">
       Similar Products
    </div>
    <div>
        <?php 
        $key=array_rand($prodIdss, 1);
       $value = $prodIdss[$key];
        $productvalue=explode('-',$value);
        $_productdata=Mage::getModel('catalog/product')->load($productvalue[0]);
        $relatedProductsId=$_product->getRelatedProductIds();
        $relatedProducts=array();
        $i=0;      
        foreach($relatedProductsId as $relatedProductId)
        {   
            $relatedProducts =  Mage::getModel('catalog/product')->load($relatedProductId);
            $relatedProducturl=$relatedProducts->getProductUrl()."/?".$prourl;
            //echo $relatedProducts->getName();
           // echo $relatedProducts->getPrice();
        ?>
        
            <li class="" style="list-style:none;background:#F0F0F0;padding:5px;margin-bottom:10px;">
                
                         <div style="">
                              <a style="width:120px;" class="" title="" href="<?php echo $relatedProducturl;?>">
                                  <img width="100" height="100" alt="" src="<?php echo $relatedProducts->getImageUrl();?>"/>
                              </a>
                          
                          <div  style="float:right;padding-top:45px;width:105px;">
                                <a href="<?php echo $relatedProducturl; ?>" style="font-size: 14px;"><?php echo $relatedProducts->getName(); ?></a>
                           </div>
                             </div>
                 
              </li>
             
       <?php  }  ?>
    </div>
</div>
 </div>
<?php if(count($collection)==0) { ?>
</div>
<?php }   ?>
 <script type="text/javascript">
     function searchproducts()
     {
         var text=document.getElementById('searchname').value;
         var url=document.getElementById('defaulturl').value;
         document.getElementById('searchform').action=url+text;
      }
 </script>



