<div class="membervideo">
<?php

$_helper = $this->helper('catalog/output');
$customer=Mage::getModel('customer/session')->getCustomer();
$customerId=$customer->getId();
$membercollection=Mage::getModel('allmembers/allmembers')->getCollection()
                        ->addFieldToFilter('customer_id',Array('eq'=>$customerId))
                        ->addFieldToFilter('status','1');
$memberIds = array();
                      
foreach($membercollection as $membervalues)
{
    $memberIds['member_id'][$membervalues['member_id']]     = $membervalues['member_id'];
    $memberIds['createddate'][$membervalues['member_id']] = $membervalues['createddate'];
}

                               
?>

<div class="page-title">
    <h1>Produkt erstellen</h1>
</div>
<?php
$collection = Mage::getModel('catalog/product')->getCollection();
$collection->addAttributeToSelect('*') ->addAttributeToFilter('member_list', array('in'=>$memberIds));

$_collectionSize = count($collection);
$_columnCount = 2; 
$i=0; $countdata=0;
foreach ($collection as $_product){
                  
                     $subdate=$memberIds['createddate'][$_product['member_list']];
                  
                     $procreateddate=$_product->getCreatedAt();
                     $productdate=explode(' ',$procreateddate);
                     $productcreatedat=$productdate[0];
                     $newproductdate= date("d/m/Y", strtotime($productcreatedat));
                                       
                     $yearlydata=explode("/",$newproductdate);
                     $year=$yearlydata[2];
                     $month=$yearlydata[1];
                     $day=$yearlydata[0];

                     $procalculation = mktime(0,0,0,date($month),date($day),date($year));
                                       
                     $subscribedate=$subdate;
                     $yearlydata1=explode("/",$subscribedate);
                     $year1=$yearlydata1[2];
                     $month1=$yearlydata1[1];
                     $day1=$yearlydata1[0];
                     $procalculation1 = mktime(0,0,0,date($month1),date($day1),date($year1));
                     $subscribetimestamp=strtotime($subscribedate);
                                        
                     if($procalculation1 <= $procalculation)
                        {
               ?>
  <?php if ($i++%$_columnCount==0): ?>

  <ul class="products-grid">
  <?php endif;?>
          <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" style="padding:12px 10px 0px;">
               <?php
                   $Id= $_product->getId();
                   $_myprodsamples = Mage::getModel('downloadable/link')->getCollection()->addProductToFilter($Id);
                    $products = Mage::getModel('catalog/product')->load($Id);
                    $type=$products['type_id'];
                    $expertid =$_product['member_list']; 
                    $attr = $_product->getResource()->getAttribute("member_list");
                    if ($attr->usesSource()): $expertname = $attr->getSource()->getOptionText($expertid); endif;
     
                    $ustreamvideo=$products['ustream_video'];
                    $enddate= explode(' ',$products[end_date]);
                    $end_date=$enddate[0];
                    $productmaterial=$products['product_material'];
             foreach ($_myprodsamples as $_sample):
                                 $video= $_sample['sample_url'];
                                $video1= $_sample['link_url'];
                            endforeach;

                            if($productmaterial=='8' &&  $video1!=NULL):
                                $audioclass='productname_audio';
                                $clas='audiovideoclass';
                            elseif($productmaterial=='7' &&  $vdata['1']!=NULL ):
                                 $audioclass='productname_video';
                                  $clas='audiovideoclass';
                           elseif($productmaterial=='7' &&  $vdata['1']==NULL ):
                                 $audioclass='productname_video';
                                  $clas='';
                            else:
                                $clas='';
                            endif;
                            $vdata=explode("v=",$video);
                            
                            if($vdata['1']!=NULL && $type=='downloadable'&& $productmaterial=='7'): ?>
                    <div class="videosclick3" onclick="thevid=document.getElementById('thevideo<?php echo $countdata ?>'); thevid.style.display='block';document.getElementById('viewplayer2<?php echo $countdata ?>').src = document.getElementById('viewplayer2<?php echo $countdata ?>').src.replace('autoplay=0','autoplay=1'); this.style.display='none'">
 
                        <?php if($products['image'] !=NULL && $products['image'] != 'no_selection'){ ?>
                                  <img style="margin:18px 18px 10px 15px;padding-left:5px;" src="<?php echo $this->helper('catalog/image')->init($products, 'small_image')->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize(290,190); ?>"  style="cursor:pointer" />
                         <?php } else { ?>
                                  <img style="margin:18px 18px 10px 15px;padding-left:5px;" src="http://img.youtube.com/vi/<?php echo $vdata['1']?>/2.jpg"  width="290" height="190" style="cursor:pointer" />
                         <?php  }  ?>
                                 <a href="javascript:void(0)" ></a>
                                  <span style="top: -200px;right:19px;" class="videotag">
                                <?php if($productmaterial=='7'): ?>
                                    <img src="<?php echo $this->getSkinUrl('images/img_video.png')?>"/>
                               <?php  endif; ?> 
                            </span>
                           </div>
                             <div id="thevideo<?php echo $countdata ?>" style="display:none"> 
                          <?php   echo  '<iframe id="viewplayer2'.$countdata.'" style="margin:15px;padding-left:5px;" title="YouTube video player" class="youtube-player" type="text/html" width="290" height="190"  src="https://www.youtube.com/embed/'.$vdata['1'].'?autoplay=0" frameborder="0" allowFullScreen></iframe>'; ?>
                            <span style="" class="videotag">
                                <?php if($productmaterial=='7'): ?>
                                    <img src="<?php echo $this->getSkinUrl('images/img_video.png')?>"/>
                               <?php  endif; ?> 
                            </span>
                             </div>
                            
                         <?php   elseif($productmaterial==8 && $video1!=NULL ): ?>
                         <script type="text/javascript" src="<?php echo $this->getSkinUrl('jwplayer/jwplayer.js'); ?>"></script>
                         <script type="text/javascript" src="<?php echo $this->getSkinUrl('jwplayer/jwplayer.html5.js'); ?>"></script>
                         <?php 
                            $_myprodsamples = Mage::getModel('downloadable/link')->getCollection()->addProductToFilter($Id);
                            foreach ($_myprodsamples as $_sample): $video= $_sample['link_url']; endforeach;
                            ?>
                         <div style="padding:15px 15px 10px 15px !important;">
                            <div id="myElementlist<?php echo $countdata ?>" class="jwwrap" class="listgrid">Loading the player...</div></div>
                            <?php 
                                  if($products['image'] !='no_selection')
                                  {
                                       $img=$this->helper('catalog/image')->init($products, 'image')->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize(290,190);
                                  }
                                  else if($products['image'] =='no_selection')
                                  {
                                       $img=$this->getSkinUrl('images/poster.jpg');
                                  }
                           ?>
                            
                            
                         <script type="text/javascript">
                                jwplayer("myElementlist<?php echo $countdata ?>").setup({
                                    image:'<?php echo $img ?>',
                                    'width': '290',
                                   'height': '190',
                                flashplayer : '<?php echo $this->getSkinUrl('jwplayer/jwplayer.flash.swf'); ?>',
                                file: "<?php echo $video1 ?>"
                              });
                        </script>
                          <span style="right: 25px; top: -200px;" class="audiotag">
                                <?php if($productmaterial=='8'): ?>
                                    <img src="<?php echo $this->getSkinUrl('images/img_audio.png')?>"/>
                               <?php  endif; ?> 
                            </span>

                <?php   else:?>
                             <div>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize(290,190); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a> 
                                <span style="  float: right;margin-left: 261px;margin-top: -195px;position: absolute;">
                                <?php if($productmaterial=='7'): ?>
                                <img src="<?php echo $this->getSkinUrl('images/img_video.png')?>"/>
                                <?php elseif($productmaterial=='8'): ?>
                                <img src="<?php echo $this->getSkinUrl('images/img_audio.png')?>"/>
                                <?php elseif($productmaterial=='10'):?>
                                <img src="<?php echo $this->getSkinUrl('images/img_ebook.png')?>"/>
                                <?php else: ?>
                                <img src="<?php echo $this->getSkinUrl('images/img_photo.png')?>"/>
                                <?php endif; ?>
                                </span>
                            </div>
                    <?php endif; ?>

                        <div class="<?php echo $clas;?>">
                    <h2 class="product-name">
                         <a href="<?php echo $_product->getProductUrl() ?>" title=""><?php echo  substr($_product->getName(), 0, 22); ?></a>
                      <div class="size">1 session: <?php echo $end_date ?></div>
                        <div class=""> <?php echo $expertname ?></div>
                    </h2>
                    <div class="price-box">
                    <span id="product-price-4" class="regular-price">
                    <span class="price">
                                    <?php  $curencySymbol =  Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
                                            echo $curencySymbol.number_format($_product->getPrice(),2); ?>   
                    </span></span>   
                </div>
                </div>
            <?php if($productmaterial=='8' || $productmaterial=='7'){ ?>
                 <div class="actions">
               <?php } else { ?>
                     <div class="actions" style="top:-20px !important;">
                     <?php } ?>
                    
                <?php if($_product['is_salable']): 
                    $base_url=MAge::getBaseUrl();?>
                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('BUY NOW') ?></span></span></button>
                <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                </div>
          </li>
 <?php } if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
 </ul>

 <?php endif ?>
<?php $countdata++; }  ?>

<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>    

 
 