<div class="forum-controls">	
		<?php if($this->getAllowFastReplyButton()): ?>
			<?php if($this->_isLogged()): ?>
				<button class="simple-forum-default-button" onclick="forumFastReplaySF();" title="<?php echo $this->__('Fast Reply'); ?>" ><?php echo $this->__('Fast Reply'); ?></button>
			<?php endif; ?>
		<?php endif; ?>	
			<button class="simple-forum-default-button" onclick="document.location.href='<?php echo $this->_getAddNewTopicUrl(); ?>'" title="<?php echo $this->__('Add New Topic'); ?>" ><span style="padding-left:11px;margin-top:3px;float:left;"><?php echo $this->__('Add New Topic'); ?></span></button>
			<button class="simple-forum-default-button" onclick="document.location.href='<?php echo $this->_getAddNewPostUrl(); ?>'" title="<?php echo $this->__('Add New Post'); ?>" ><span style="padding-left:11px;margin-top:3px;float:left;"><?php echo $this->__('Add New Post'); ?></span></button>
	
</div>
<?php if($this->getAllowFastReplyButton() && $this->_isLogged()): ?>
	<?php echo $this->getInitTiny() ?>
<?php endif; ?>