<?php 
	$_coreHelper = $this->helper('core');
	$_taxHelper  = $this->helper('tax');
	$_helper = $this->helper('catalog/output');	
	$_dealCollection = $this->getDeals(); 
	$_collectionSize = count($_dealCollection);
			$timechange = (int)Mage::getStoreConfig('dailydeal/general/timechange'); 
	
	if ($_collectionSize > 0){
		foreach ($_dealCollection as $_deal){
			$dealqty = $_deal->getDealQty();
			$soldqty = $_deal->getSoldQty();
			$gmtcore = Mage::getSingleton('core/date')->getGmtOffset();
			
			$beforetime = Mage::getModel('core/date')->timestamp(time())-strtotime($_deal->getStartDateTime());//echo $beforetime;
			$aftertime = strtotime($_deal->getEndDateTime())- Mage::getModel('core/date')->timestamp(time());//echo $aftertime;
			if ($dealqty > $soldqty && ($aftertime > 0) && ($beforetime >= 0)){
			$_product = Mage::getModel('catalog/product')->load($_deal->getProductId());	
?>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->getSkinUrl('mw_dailydeal/symbolic/css/symgeneral.css');?>"/>
<div class="symbolic_clear">&nbsp;</div>

<div class="deal">
	<div class="deal-title">
		<h1 class="deal-name" title="<?php echo $_product->getName()?>"><?php echo $_product->getName()?></h1>
	</div>
	<div class="deal-info">
	
		<div class="deal-info-top">
			<div class="leftcol">
	
	<?php 
		$_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice(), $_simplePricesTax);
		$_finalPrice = $_taxHelper->getPrice($_product, $_product->getFinalPrice());
		$save = $_regularPrice-$_finalPrice;
		$discount = ($save/$_regularPrice)*100;
		
	?>
				<div class="content-symbolicdeal">
	
					<div class="price_tag">
						<div class="price_tag_inner">
							<div class="amount"><?php echo $_coreHelper->currency($_finalPrice,true,false) ?></div>	
							
							<div class="btn_buy">
								<p>
									<button type="button" title="<?php echo Mage::helper('dailydeal')->__('Buy !') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span>
										<span><?php echo Mage::helper('dailydeal')->__('Buy !') ?></span></span>
									</button>
								</p>								
							</div>
						</div>
					</div>
					
				    <div class="deal_discount" class="clearfix">
						  <dl>
							<dt><?php echo Mage::helper('dailydeal')->__('Old price'); ?></dt>
							<dd><?php echo $_coreHelper->currency($_regularPrice,true,false) ?></dd>
						  </dl>
						  <dl class="discount">
							<dt><?php echo Mage::helper('dailydeal')->__('Discount'); ?></dt>
							<dd><?php echo round($discount,2).'%'?></dd>
						  </dl>
						  <dl class="save">
							<dt><?php echo Mage::helper('dailydeal')->__('You Save'); ?></dt>
							<dd><?php echo $_coreHelper->currency($save,true,false)?></dd>
						  </dl>
						  <div class="clear"></div>
					</div>
				
					<div id="gift_a_deal">
						<div style="padding-left: 0px;font-size: 11px;">
						<?php if (($dealqty-$soldqty) > 10){?>
							
							<?php echo Mage::helper('dailydeal')->__('There are <span class="deal-qty">%s items</span> available.',$dealqty-$soldqty); ?>
						
						<?php } elseif (($dealqty-$soldqty) <= 10 && ($dealqty-$soldqty) > 1) {?>
							
							<?php echo Mage::helper('dailydeal')->__('Hurry, there are only <span class="deal-qty">%s items</span> left!',$dealqty-$soldqty); ?>
						
						<?php }elseif (($dealqty-$soldqty) == 1){?>
							
							<?php echo Mage::helper('dailydeal')->__('Hurry, there is only <span class="deal-qty">%s item</span> left!',$dealqty-$soldqty); ?>
						
						<?php }?>	
						</div>
					</div>	
										
														
					<div class="remaining_time">
						<p class="timer_text"><?php echo Mage::helper('dailydeal')->__('Time left to Buy'); ?></p>
									<!-- Countdown Javascript -->
							<div id="counter" class="symbolic">
								<ul class="countdown">
									<li class="first"><div class="countdown_num" id="symbolic_cd_hour-<?php echo $_deal->getDailydealId()?>"></div><div id="hour-sym"><?php echo Mage::helper('dailydeal')->__('Hours'); ?></div></li>
									<li><div class="countdown_num" id="symbolic_cd_min-<?php echo  $_deal->getDailydealId()?>"></div><div id="minute-sym"><?php echo Mage::helper('dailydeal')->__('Minutes'); ?></div></li>
									<li class="last"><div class="countdown_num" id="symbolic_cd_sec-<?php echo  $_deal->getDailydealId()?>"></div><div id="second-sym"><?php echo Mage::helper('dailydeal')->__('Seconds'); ?></div></li>
								</ul>
								<div class="clear"><span>&nbsp;</span></div>
							</div>
								<div id="expired" style="display:none;">
									The deadline has passed.
								</div>
				
						<script type="text/javascript">
							function addLoadEvent(func) {
							  var oldonload = window.onload;
							  if (typeof window.onload != 'function') {
							    window.onload = func;
							  } else {
							    window.onload = function() {
							      if (oldonload) {
							        oldonload();
							      }
							      func();
							    }
							  }
							}
							
							addLoadEvent(function() {
								 countDown4(<?php echo date('Y',strtotime($_deal->getEndDateTime()));?>, 
											<?php echo date('m',strtotime($_deal->getEndDateTime()));?>, 
											<?php echo date('d',strtotime($_deal->getEndDateTime()));?>,
										  	<?php echo date('H',strtotime($_deal->getEndDateTime()));?>,
											<?php echo date('i',strtotime($_deal->getEndDateTime()));?>,
											  "symbolic_cd_hour-<?php echo $_deal->getDailydealId()?>",
											  "symbolic_cd_min-<?php echo  $_deal->getDailydealId()?>",
											  "symbolic_cd_sec-<?php echo  $_deal->getDailydealId()?>");
							});
						</script>     
					</div>						
					
				</div>	
					
					
				<div class="share">
					<!-- AddThis Button BEGIN -->
					<div class="addthis_toolbox addthis_default_style ">
					
						<table border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td><a class="addthis_button_facebook_like" fb:like:layout="button_count"></a></td>
								<td><a class="addthis_button_tweet"></a></td>
							</tr>
							<tr>
								<td><a class="addthis_button_pinterest_pinit"></a></td>
								<td><a class="addthis_counter addthis_pill_style"></a></td>
							</tr>
						</table>
					
					</div>
					<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-5018d6a958afb330"></script>
					<!-- AddThis Button END -->
				</div>
	
			</div>
	
	
			<div class="rightcol">						
				<div class="media">	
				<img id="image" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')?>" alt="<?php $this->htmlEscape($this->getImageLabel())?>" title="<?php $this->htmlEscape($this->getImageLabel())?>" width="420" height="267"/>
				</div>						
				<div class="info">	
					<?php if ($_product->getShortDescription()):?>
				                <div class="short-description">
				                    <h2><?php echo Mage::helper('dailydeal')->__('Quick Overview') ?></h2>
				                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
				                </div>
				            <?php endif;?>				
				</div>
			
			</div>
			
			
		</div>
		
		<div class="clear"></div>				
		<div class="mw_deal-tabs" >
			<ul class="mw_1-product-tabs mw_info-tabs" >
				<li class="description-content">
					<div class="product_tabs_description_contents"> 
						<?php $_description = $_product->getDescription(); ?>
						<?php if ($_description): ?>
							<h2><?php echo Mage::helper('dailydeal')->__('Description') ?></h2>
							<div class="std">
								<?php echo $this->helper('catalog/output')->productAttribute($_product, $_description, 'description') ?>
							</div>
						<?php endif; ?>				
				   </div>	
				</li>
								
				<li id="Reviews-content">		      
				    <div class="product_tabs_description_contents"> 				
						<h2><?php echo Mage::helper('dailydeal')->__('Review') ?></h2>
						<div class="std">
        <dl>
        <?php $_items = $this->getReviewsCollection($_deal->getProductId())->getItems();?>
		<?php if (count($_items)){?>
        <?php foreach ($_items as $_review):?>
            <dt>
                <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo $this->htmlEscape($_review->getTitle()) ?></a> <?php echo $this->__('Review by <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?>
            </dt>
            <dd>
				<div class="rating-box">
					<div class="rating" style="width:<?php echo $this->__getPercentRate($_review); ?>%;"></div>
				</div>
                <?php echo nl2br($this->htmlEscape($_review->getDetail())) ?>
                <small class="date"><?php echo $this->__('(Posted on %s) long', $this->formatDate($_review->getCreatedAt())) ?></small>
            </dd>
        <?php endforeach; ?>
        <?php }else{?>
        	<dd>
        		<span><?php echo Mage::helper('dailydeal')->__('There is no review for this product currently.');?></span>
        	</dd>
        <?php }?>
        </dl>	

			            </div>	
					</div>
				</li>			
			</ul>
       		<div style="clear:both;height:0;"></div>
		</div>

	</div>
</div>
		<?php break;?>
	<?php }/*if (($aftertime > 0) && ($beforetime >= 0)){*/?>
<?php }/*foreach ($_dealCollection as $_deal){*/?>
<?php }else{/*if ($_collectionSize > 0){*/?>
        	<p class="note-msg"><?php echo Mage::helper('dailydeal')->__('There is no review for this product currently.');?></p>        	
        <?php }?>