<table class="tab-deal">
	<tr>
		<td>
			<a href="<?php echo $this->getUrl(Mage::helper('dailydeal')->getRewriteUrl('dailydeal/index ')); ?>">
				<span><span><?php echo $this->__('Active Deals');?></span></span>
			</a>
		</td>
		<td>
			<a href="<?php echo $this->getUrl(Mage::helper('dailydeal')->getRewriteUrl('dailydeal/past')); ?>">
				<span><span><?php echo $this->__('Past Deals');?></span></span>
			</a>
		</td>
		<td class="active">
			<a href="<?php echo $this->getUrl(Mage::helper('dailydeal')->getRewriteUrl('dailydeal/comming')); ?>">
				<span><span><?php echo $this->__('Comming Deals');?></span></span>
			</a>
		</td>
	</tr>
</table>

<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
	$_coreHelper = $this->helper('core');
	$_taxHelper  = $this->helper('tax');
    $_commingdealsCollection=$this->getCommingdeals();
    $_helper = $this->helper('catalog/output');
 	$outputFormat = Mage::app()->getLocale()->getDateTimeFormat(Mage_Core_Model_Locale::FORMAT_TYPE_LONG);
    
?>
<?php if(!$_commingdealsCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_commingdealsCollection as $_commingdeal): ?>
    <?php 
    $dealqty = $_commingdeal->getDealQty();
    $_product = Mage::getModel('catalog/product')->load($_commingdeal->getProductId());?>
        <li class="item<?php if( ++$_iterator == sizeof($_commingdealsCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php //echo $this->getPriceHtml($_product, true) ?>
                     <?php $_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice()) ?>		
					<?php $_finalPrice = $_commingdeal->getDailydealPrice()?>
					<p class="old-price" >
						<?php echo Mage::helper('dailydeal')->__('Regular Price:'); ?>
						<span class="regular-price">
							  <span class="price"><?php echo $_coreHelper->currency($_regularPrice,true,false) ?></span>
						</span>
					</p>
					<p class="special-price">
		                <span class="price">
		                    <?php echo Mage::helper('dailydeal')->__('Special price:'); ?><?php echo $_coreHelper->currency($_finalPrice,true,false) ?>
		                </span>
		            </p>
		            <p>
		            	<?php echo Mage::helper('dailydeal')->__('There are <span class="deal-qty-red">%s items</span> available.',$dealqty); ?>
		        	</p>
	 				<?php $startdatetime= strtotime($_commingdeal->getStartDateTime());?>
	        		<p>
	        			<?php echo Mage::helper('dailydeal')->__('Deal starts at: <h4>%s</h4>',date(' d F, Y H:i',$startdatetime)); ?>
	        		</p>    
               
                </div>
            </div>
            
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php 
    	$_collectionSize = $_commingdealsCollection->count(); 
    	$_columnCount = 3;
    ?>
    <?php $i=0; foreach ($_commingdealsCollection as $_commingdeal): ?>
    <?php 			
        $dealqty = $_commingdeal->getDealQty();
    
    $_product = Mage::getModel('catalog/product')->load($_commingdeal->getProductId());
    ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php //echo $this->getPriceHtml($_product, true) ?>
                  <?php $_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice(), $_simplePricesTax) ?>		
				<?php $_finalPrice = $_commingdeal->getDailydealPrice()?>
				<p class="old-price" >
					<?php echo Mage::helper('dailydeal')->__('Regular price:'); ?>
					<span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>-related">
						  <span class="price"><?php echo $_coreHelper->currency($_regularPrice,true,false) ?></span>
					</span>
				</p>
				<p class="special-price">
	                <span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
	                    <?php echo Mage::helper('dailydeal')->__('Special price:'); ?> <?php echo $_coreHelper->currency($_finalPrice,true,false) ?>
	                </span>
	            </p>
	       		<p>
 					<?php echo Mage::helper('dailydeal')->__('There are <span class="deal-qty">%s items</span> available',$dealqty); ?>
 				</p>
 				<?php $startdatetime= strtotime($_commingdeal->getStartDateTime()); ?>
        		<p>
        			<?php echo Mage::helper('dailydeal')->__('Deal starts at <h4 class="deal-time">%s</h4>',date(' d F, Y H:i',$startdatetime)); ?> 
        		</p>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
