<table class="tab-deal">
	<tr>
		<td>
			<a href="<?php echo $this->getUrl('dailydeal'); ?>">
				<span><span><?php echo $this->__('Aktuelle Deals');?></span></span>
			</a>
		</td>
		<td>
			<a href="<?php echo $this->getUrl('dailydeal/past'); ?>">
				<span><span><?php echo $this->__('Vergangene Deals');?></span></span>
			</a>
		</td>
		<td>
			<a href="<?php echo $this->getUrl('dailydeal/comming'); ?>">
				<span><span><?php echo $this->__('Zukünftige Deals');?></span></span>
			</a>
		</td>
	</tr>
</table>
