<?php 

/**
 * Contus Support Interactive.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file PRICE COUNTDOWN-LICENSE.txt.
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento 1.4.x and 1.5.x COMMUNITY edition
 * Contus Support does not guarantee correct work of this package
 * on any other Magento edition except Magento 1.4.x and 1.5.x COMMUNITY edition.
 * =================================================================
 */
?>

<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<?php
$currenttime = date('Y-m-d H:i:s',Mage::getModel('core/date')->timestamp(time()));
$_deal = Mage::getModel('dailydeal/dailydeal')->getCollection()->loadcurrentdeal($_product->getId());

if ($_deal){
	$title = Mage::getStoreConfig('dailydeal/general/productdetaillabel');
	$gmtcore = Mage::getSingleton('core/date')->getGmtOffset();//var_dump($gmtcore*1000);die;
	$currenttime = Mage::getModel('core/date')->timestamp(time());//var_dump($_deal->getEndDateTime());
	$beforetime = $currenttime - strtotime($_deal->getStartDateTime());
	$aftertime = strtotime($_deal->getEndDateTime())- $currenttime;
	$timechange = (int)Mage::getStoreConfig('dailydeal/general/timechange'); 
	$dealqty = $_deal->getDealQty();
	$soldqty = $_deal->getSoldQty();
	
	//if (($soldqty < $dealqty) && ($aftertime > 0) && ($beforetime >= 0)){  - 
?>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('mw_dailydeal/css/superneat.css')?>" type="text/css" media="all"/>
	<div class="deal-product">
		<div class="catalogproductview">
			<?php if ($title == ''){?>
			<h3><?php echo $this->__('Get it before it&acute;s gone!');?></h3>
			<?php }else {?>
			<h3 style="color: white;padding:0; margin:0; line-height:40px; "><?php echo $title;?></h3>
			<?php }?>
			</div>
		<div class="ct-deal-pro">
			<!-- Countdown Javascript -->
			<div id="counter" class="counter">
				<ul class="countdown">	
					 <li class="first"><div class="countdown_num" id="view_cd_hour-<?php echo $_deal->getDailydealId()?>"></div><div id="hour">Hours</div></li>
					<li><div class="countdown_num" id="view_cd_min-<?php echo  $_deal->getDailydealId()?>"></div><div id="minute">Minutes</div></li>
					<li class="last"><div class="countdown_num" id="view_cd_sec-<?php echo  $_deal->getDailydealId()?>"></div><div id="second">Seconds</div></li>
				</ul>
			</div>
			<div id="expired" style="display:none;">
				<?php echo Mage::helper('dailydeal')->__('The deadline has passed.');?>
			</div>
			<script type="text/javascript">
					function addLoadEvent(func) {
					  var oldonload = window.onload;
					  if (typeof window.onload != 'function') {
						window.onload = func;
					  } else {
						window.onload = function() {
						  if (oldonload) {
							oldonload();
						  }
						  func();
						}
					  }
					}
				
				addLoadEvent(function() {
					 countDown3(<?php echo date('Y',strtotime($_deal->getEndDateTime()));?>, 
								<?php echo date('m',strtotime($_deal->getEndDateTime()));?>, 
								<?php echo date('d',strtotime($_deal->getEndDateTime()));?>,
								<?php echo date('H',strtotime($_deal->getEndDateTime()));?>,
								<?php echo date('i',strtotime($_deal->getEndDateTime()));?>,
								  "view_cd_hour-<?php echo $_deal->getDailydealId()?>",
								  "view_cd_min-<?php echo  $_deal->getDailydealId()?>",
								  "view_cd_sec-<?php echo  $_deal->getDailydealId()?>");
				});
			</script>     
			<div class="clear"><span>&nbsp;</span></div>
			<div class="qty-deal">
				<span>
					<?php if (($dealqty-$soldqty) > 10){?>
						<?php echo Mage::helper('dailydeal')->__('There are <span class="deal-qty">%s items</span> available.',$dealqty-$soldqty); ?>
					<?php } elseif(($dealqty-$soldqty) <= 10 && ($dealqty-$soldqty) > 1) {?>
						<?php  echo Mage::helper('dailydeal')->__('Hurry, there are only <span class="deal-qty">%s items</span> left!',$dealqty-$soldqty); ?>
					<?php } elseif (($dealqty-$soldqty) == 1){?>
						<?php echo Mage::helper('dailydeal')->__('Hurry, there is only <span class="deal-qty">%s item</span> left!',$dealqty-$soldqty); ?>
					<?php }?>	
				</span>
			</div>
		</div>					
	</div>
<?php //echo $this->getChildHtml('product_type_data_extra') ?>
<?php //echo $this->getPriceHtml($_product);?>

<?php 
	//}
}else { ?>



<?php }?>
