<?php
/**
 * Mage World
 *
 * NOTICE OF LICENSE

 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2012 Mage World (http://www.mageworld.com)
 */
/**
 * 
 *
 * @category   MW
 * @package    MW_Dailydeal
 * @author     Magento Developer <chinhbt@asiaconnect.com.vn>
 */
?>
<?php //Zend_Debug::dump($this->getCollection());die();
//$now   = new DateTime();
$month = date("m");
$year = date("Y");
$currFromDate = $month.'/01/'.$year;//alert(fromdate);
if (($month == 02) && ($year%4 == 0)){
	$currToDate = $month.'/29/'.$year;
}else if (($month == 02) && ($year%4 != 0)){
	$currToDate = $month.'/28/'.$year;
}else if (($month == 04) || ($month == 09) || ($month == 06) || ($month == 11)){
	$currToDate = $month.'/30/'.$year;
}else {
	$currToDate = $month.'/31/'.$year;
}
if($this->getCollection()): ?>
 <?php if($this->canDisplayContainer()){ ?>
        <?php if($this->getGridHeader()): ?>
        <div class="content-header">
            <table cellspacing="0">
                <tr>
                    <td style="width:50%;"><h2><?php echo $this->getGridHeader(); ?></h2></td>
                </tr>
            </table>
        </div>
        <?php endif; /*if($this->getGridHeader()):*/?>
        <div id="<?php echo $this->getId() ?>">
    <?php }else{ ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
    <?php } /*if($this->canDisplayContainer()){*/?>
    <?php if($this->getStoreSwitcherVisibility() || $this->getDateFilterVisibility()){ ?>
    	<!-- Select Website --><!--
        
        --><!-- End Select Website -->
        <!-- Actions -->
		 <table cellspacing="0" class="actions">
            <tr>
        <?php if($this->getDateFilterVisibility()): ?>
            <td class="a-left filter">
                    <input class="input-text no-changes" type="hidden" value="<?php echo $currFromDate; ?>" id="period_date_from" name="report_from" /> 

                  <input  class="input-text no-changes " type="hidden" value="<?php echo $currToDate; ?>" id="period_date_to" name="report_to"  /> 
            	
                <div class="f-left">                
	                <div><?php echo $this->__('Year') ?>&nbsp           	
                		<form name="formyear">
                		<select id="year" name="year" onchange="updatetext()">
                		<?php for ($i=0;$i<11;$i++){?>
                			<?php if ($i != 5){?>
							<option value="<?php echo date('Y',time())-5+$i?>"><?php echo date('Y',time())-5+$i?></option>
							<?php }else{?>
							<option selected="selected" value="<?php echo date('Y',time())-5+$i?>"><?php echo date('Y',time())-5+$i?></option>
							<?php }?>
						<?php }?>
						</select></form>
                	</div>
                	</div>
                	<div class="f-left" style="padding-left: 20px;"> 
                	<div><?php echo $this->__('Month') ?>   &nbsp  <form name="formmonth">
                		<select id="month" name="month" onchange="updatetext()">
                			<option value='0' selected="selected">---Select month---</option>
							<option value='01' >January</option>
							<option value='02' >February</option>
							<option value='03' >March</option>
							<option value='04'>April</option>
							<option value='05'>May</option>
							<option value='06'>June</option>
							<option value='07'>July</option>
							<option value='08'>August</option>
							<option value='09'>September</option>
							<option value='10'>October</option>
							<option value='11'>November</option>
							<option value='12'>December</option>
						</select>
						</form>
                	</div>
                </div>
                <div class="f-left" style="padding-left: 20px;">
                	<?php echo $this->getRefreshButtonHtml() ?>
                </div>
                <script type="text/javascript">

             function updatetext()
                {
					var objyear = document.formyear.year;
					var objmonth = document.formmonth.month;
					var	yearselect = objyear.options[objyear.selectedIndex].value;
                	var monthselect = objmonth.options[objmonth.selectedIndex].value;
					var fromdate = monthselect+'/01/'+yearselect;//alert(fromdate);

					if ((monthselect == 02) && (yearselect%4 == 0)){
						var todate = monthselect+'/29/'+yearselect;
					}else if ((monthselect == 02) && (yearselect%4 != 0)){
						var todate = monthselect+'/28/'+yearselect;
					}else if ((monthselect == 04) || (monthselect == 09) || (monthselect == 06) || (monthselect == 11)){
						var todate = monthselect+'/30/'+yearselect;
					}else {
						var todate = monthselect+'/31/'+yearselect;
					}//alert(todate);
                    document.getElementById("period_date_from").value = fromdate;
                    document.getElementById("period_date_to").value = todate;

                } 
                </script>
            </td> 
            <?php endif;/*if($this->getDateFilterVisibility()):*/?>
         
            </tr>
            </table>
            <?php }?>
            <?php if($this->getMassactionBlock()->isAvailable()): ?>
<?php echo $this->getMassactionBlockHtml() ?>
<?php endif ?>
<!-- Create Grid --> 
   <div class="grid">
    <table cellspacing="0" class="data" id="<?php echo $this->getId() ?>_table">
        <col/>
        <?php foreach ($this->getColumns() as $_column): ?>
        <col <?php echo $_column->getHtmlProperty() ?>/>
        <?php endforeach; ?>
        <?php if ($this->getHeadersVisibility() || $this->getFilterVisibility()): ?>
            <thead>
                <?php if ($this->getHeadersVisibility()): ?>
                    <tr class="headings">
                    <th class="no-link" style="width:100px"><span class="no-br"><?php echo $this->getPeriodText() ?></span></th>
                    <?php foreach ($this->getColumns() as $_column): ?>
                        <th <?php echo $_column->getHeaderHtmlProperty() ?>><span class="no-br"><?php echo $_column->getHeaderHtml() ?></span></th>
                    <?php endforeach; ?>
                    </tr>
                <?php endif; ?>
            </thead>
        <?php endif; ?> 
        <tbody>
        <?php if ($this->getCollection()->getSize()): ?>
        <?php foreach ($this->getCollection()->getIntervals() as $_index => $_item){ ?>                           
            <?php 
            	$report = Mage::getModel('dailydeal/dailydeal')->getCollection()
            			->addFieldToFilter('start_date_time',array('from' => $_item['start'], 'to' => $_item['end']));
            			?>
            <?php $rows=count($report);?>
            <?php if ($rows > 0 ){ ?>
             <tr title="<?php echo $this->getRowUrl($_item) ?>"<?php if ($_class = $this->getRowClass($_item)):?> class="<?php echo $_class; ?>"<?php endif;?>>
            <td rowspan="<?php echo $rows + ($this->getCountTotals() && $this->getSubtotalVisibility()?1:0) + 1 ?>"><?php echo $_index ?></td>
                <?php $i=0;foreach ($report as $_subIndex=>$_subItem):?>
                    <?php if($i>0): ?>
                    <!-- hang chua du lieu -->
                    <tr title="<?php echo $this->getRowUrl($_item) ?>"<?php if ($_class = $this->getRowClass($_item)):?> class="<?php echo $_class; ?>"<?php endif;?>>
                    <?php endif; ?>
                    <?php $i++; ?>
                    <?php $j=0;                    
                    foreach ($this->getColumns() as $_column): 
                   // Zend_Debug::dump($_column);?>
                        <td class="<?php echo $_column->getCssProperty() ?> <?php echo ++$j==$numColumns?'last':'' ?>">
                            <?php echo (($_html = $_column->getRowField($_subItem)) != '' ? $_html : '&nbsp;') ?>
                            
                        </td>
                    <?php endforeach; ?>
                    </tr>                    
                <?php endforeach; ?>
            		 <!-- hang phu -->
                    <tr title="<?php echo $this->getRowUrl($_item) ?>"<?php if ($_class = $this->getRowClass($_item)):?> class="<?php echo $_class; ?>"<?php endif;?>>
	                <?php for ($i=0;$i<8;$i++){?>
	                <td></td>
	                <?php }?>
	                <td><a href="<?php echo  Mage::helper('adminhtml')->getUrl('dailydeal/adminhtml_dealitems/newdaily/',array('start'=> $_index)); ?>">Add deal</a></td>
                    </tr>
            <?php }else{ ?>
            </tr>
            <tr  title="<?php echo $this->getRowUrl($_item) ?>"<?php if ($_class = $this->getRowClass($_item)):?> class="<?php echo $_class; ?>"<?php endif;?>>
                <?php //var_dump($_item);?>
                <td ><?php echo $_item['title'];?></td>
                <?php for ($i=0;$i<8;$i++){?>
                <td></td>
                <?php }?>
                <td><a href="<?php echo Mage::helper('adminhtml')->getUrl('dailydeal/adminhtml_dealitems/newdaily/',array('start'=> $_item['start']))?>"  >Add deal</a></td>
              
            </tr><?php //echo $_item['start'];?>
            <?php } ?>
            <script type="text/javascript">
            var objyearafter = document.formyear.year;
           <?php if (!empty($_item)){?>
            	document.formmonth.month.value = '<?php echo date('m',strtotime($_item['start']));?>';
            	<?php } else break;?>
            	objyearafter.value = '<?php echo date('Y',strtotime($_item['start']));?>';
            </script>
            
        <?php } ?>
       
        <?php endif; ?>
        </tbody>

    </table>
    </div>
<!-- End Create Grid -->
<?php if ($this->canDisplayContainer()):?>
</div>         
<script type="text/javascript">
<!--
//init JS Object 
<?php echo $this->getJsObjectName() ?> = new varienGrid('<?php echo $this->getId() ?>', '<?php echo $this->getGridUrl() ?>', '<?php echo $this->getVarNamePage() ?>', '<?php echo $this->getVarNameSort() ?>', '<?php echo $this->getVarNameDir() ?>', '<?php echo $this->getVarNameFilter() ?>');
<?php echo $this->getJsObjectName() ?>.useAjax = '<?php echo $this->getUseAjax() ?>';//alert(document.formmonth.month.value);
if ((location.href.indexOf('filter') <= 0) && (document.formmonth.month.value == '0')){ 
	var date = new Date();//alert(date);alert(date.getMonth());
	var objyear = document.formyear.year;
	var	yearselect = objyear.options[objyear.selectedIndex].value;
	var monthselect = date.getMonth()+1;//alert(monthselect);
	var fromdate = monthselect+'/01/'+yearselect;//alert(fromdate);

	if ((monthselect == 02) && (yearselect%4 == 0)){
		var todate = monthselect+'/29/'+yearselect;
	}else if ((monthselect == 02) && (yearselect%4 != 0)){
		var todate = monthselect+'/28/'+yearselect;
	}else if ((monthselect == 04) || (monthselect == 09) || (monthselect == 06) || (monthselect == 11)){
		var todate = monthselect+'/30/'+yearselect;
	}else {
		var todate = monthselect+'/31/'+yearselect;
	}//alert(todate);
    document.getElementById("period_date_from").value = fromdate;
    document.getElementById("period_date_to").value = todate;
	<?php echo $this->getJsObjectName();?>.doFilter();
}
<?php if($this->getMassactionBlock()->isAvailable()): ?>
<?php echo $this->getMassactionBlock()->getJavaScript() ?>
<?php endif ?>
/* Overwrite function from switcher.phtml widget*/
function switchStore(obj){
    if (obj.options[obj.selectedIndex].getAttribute('website') == 'true') {
        var selectionType = 'website';
    } else if (obj.options[obj.selectedIndex].getAttribute('group') == 'true') {
        var selectionType = 'group';
    } else {
        var selectionType = 'store';
    }
    var storeParam = obj.value ? selectionType + '/' + obj.value + '/' : '';
    if(obj.switchParams){
        storeParam+= obj.switchParams;
    }
    var formParam = new Array('period_date_from', 'period_date_to', 'report_period');
    var paramURL = '';
    var switchURL = '<?php echo $this->getAbsoluteGridUrl(array('_current' => false)); ?>'.replace(/(store|group|website)\/\d+\//,'');

    for(var i=0;i<formParam.length;i++){
        if ($(formParam[i]).value && $(formParam[i]).name) {
            paramURL+= $(formParam[i]).name + '=' + escape($(formParam[i]).value) + '&';
        }
    }
    setLocation(switchURL + storeParam + '?' + paramURL);
}
//-->
</script>        
<!-- End Actions -->

<?php endif;/*if($this->getStoreSwitcherVisibility() || $this->getDateFilterVisibility()):*/?>
<?php endif;/*if($this->getCollection())*/?>