<?php $_helper = $this->helper('catalog/output'); ?>
<?php $extIdentifier = Mage::helper('events')->extIdentifier();?>
<div class ='events_land'>

<!-- Please remove whole block once breadcrumb function is added -->
<div style="clear:both; height:5px;"></div>
<div class="breadcrumbs">
  <ul>
    <li><?php //echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?></li>
  </ul>
</div>
<!-- end of comment -->

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection(); ?>
<!-- div class="page-title" -->
    <h1><?php //echo $this->__($this->getTitle()) ?>Now Broadcasting</h1>
<!-- /div -->

<!-- Use this pagination instead of the one above -->
    
    <div id="sortNav" style="overflow:auto;padding:25px">
    <!--  <form method="" action="">
        <div style="float:left">
        <label style="padding-right:10px;">Show</label>
        <select style="width:70px;">
          <option>9</option>
          <option>15</option>
          <option>30</option>
          <option>All</option>
        </select>
        <label style="padding-left:10px; padding-right:0;">1-9 of 285</label>
        </div>
        <div id="navPage" style="margin-top:7px;">
      <ul class="list">
        <li><a href="">&laquo;</a></li>
        <li class="currentPage">1</li>
        <li><a href="">2</a></li>
        <li><a href="">3</a></li>
        <li><a href="">4</a></li>
        <li><a href="">5</a></li>
        <li><a href="">&raquo;</a></li>
      </ul>
    </div>
      </form>-->
	</div> 
    <!--<div class="clear" style="height:15px;"></div>
	
    
    <div class="clear" style="height:25px;"></div>-->
    <!-- end of filtering -->
    <div class="toolbarevents" style="margin-top:-15px;">
<?php echo $this->getToolbarHtml(); ?>
    </div>
<?php $this->getMode('grid');$mode='grid'; if($collection->getSize()):  ?>
<?php  ?>
	<?php if($mode!='grid'): ?>
	<!-- List Model -->
	<?php $_iterator = 0;  ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($collection as $c): 
			$thumbImgList = '';
		if ($c->getEventImage() != ''):
			$thumbImgList =  Mage::getBaseUrl('media').$c->getEventThumbImage();
               
              
                endif;
    	$event = Mage::getModel('catalog/category')->load($c->getId());
		$str = $c->getEventContent();
		if (strlen($str) > 150):
				$str = substr($str,0,100)." ...";
		endif;
                
		?>
        <li class="item<?php if( ++$_iterator == sizeof($collection) ): ?> last<?php endif; ?>">
            <?php if ($thumbImgList): ?>
				<a href="<?php echo Mage::helper('events')->customUrl($c->getEventUrlPrefix()); ?>" title="<?php echo $this->stripTags($c->getEventTitle()); ?>" class="product-image">
				<img src="<?php echo $thumbImgList; ?>" width="135" height="135" alt="<?php echo $this->stripTags($c->getEventTitle()); ?>" /></a>
			<?php endif; ?>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_eventNameStripped = $this->stripTags($c->getEventTitle(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo Mage::helper('events')->customUrl($c->getEventUrlPrefix()); ?>" title="<?php echo $_eventNameStripped; ?>"><?php echo $c->getEventTitle(); ?></a></h2>
					<h2 class="product-name">Venue: <?php echo $c->getEventVenu(); ?></h2>
					<b>From:</b> <?php echo date('Y M d - h:i a', strtotime($c->getEventStartDate())); ?><br/> <b>To: </b><?php echo date('Y M d - h:i a', strtotime($c->getEventEndDate())); ?>
                    <div class="desc std">
                        <?php echo $str; ?>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
	<?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $collection->count() ?>
    <?php 
    	$_columnCount =3;
     //  echo "<pre>";print_r($collection->getData());die('helo');
    ?>
    <?php $i=0; foreach ($collection as $c):
    $c = Mage::getModel('events/events')->load($c->getEventId());
    $connection = Mage::getSingleton('core/resource')->getConnection('core_read');
    $query="select * from events_product where eventid=".$c->getEventId();
    $result=$connection->query($query)->fetch();
    $liveproduct=Mage::getModel('catalog/product')->load($result['product_id']);
    $expertid =$liveproduct['member_list']; 
    $attr = $liveproduct->getResource()->getAttribute("member_list");
    if ($attr->usesSource()): $expertname = $attr->getSource()->getOptionText($expertid); endif;
	$thumbImgGrid = '';
	if ($c->getEventImage() == ''):
		$thumbImgGrid = $this->helper('catalog/image')->init($liveproduct, 'image')->keepAspectRatio(FALSE)->keepFrame(FALSE)->resize(290,190);
	endif;
    ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
				<?php if ($thumbImgGrid): ?>
					<a style="  display: block; margin: 15px;padding-left: 5px;"href="<?php echo Mage::helper('events')->customUrl($c->getEventUrlPrefix()) ?>" title="<?php echo $this->stripTags($c->getEventTitle()); ?>" class="product-image">
					<img src="<?php echo $thumbImgGrid;?>" /></a>
				<?php endif; ?>
                <?php
                
                ?>
                <h2 class="product-name">
                    <a href="<?php echo Mage::helper('events')->customUrl($c->getEventUrlPrefix()); ?>"><?php echo $c->getEventTitle() ?></a>
                    <div style="color:#666666;font-size:12px;"><?php echo $expertname; ?></div>
                
                </h2>
				<!--<b>From:</b> <?php echo date('Y M d - h:i a', strtotime($c->getEventStartDate())); ?><br/>
				<b>To: </b><?php echo date('Y M d - h:i a', strtotime($c->getEventEndDate())); ?>-->
                <div class="price-box">
                              <span style=" float: left;margin-left: 18px;margin-top: 10px;">
                                  <a style="text-decoration:none;color:#fff;" href="<?php echo Mage::helper('events')->customUrl($c->getEventUrlPrefix()) ?>" title="<?php echo $this->stripTags($c->getEventTitle()); ?>" class="">
					WATCH
                                  </a>
                              </span>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

<?php //echo $this->getToolbarHtml(); ?>
<?php else: ?>
    <p><?php echo Mage::helper('events')->errMsg(); ?></p>
	<a href="<?php echo $_SERVER ['HTTP_REFERER']; ?>">zurück << </a>
<?php endif ?>
</div>
