<?php

 $customer=Mage::getModel('customer/session')->getCustomer();
 $customerId=$customer->getId();
 $membercollection=Mage::getModel('allmembers/allmembers')->getCollection()->addFieldToFilter('customer_id',Array('eq'=>$customerId));
?>
<div class="page-title">
    <h1>Member Videos</h1>
</div>
<?php
    echo $this->getToolbarHtml();
    $collection=$this->getCollection();
     
    $_collectionSize = $collection->count()?>
    <?php if($this->getMode()!='grid'): ?>
	<!-- List Model -->
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
       <?php $i=0; foreach ($collection as $_product): ?>
        <?php  foreach($membercollection as $memberInfo)
                {
                    $memberId=$memberInfo['member_id'];
                    $subdate=$memberInfo['createddate'];
                    break;
                }
                     $procreateddate=$_product->getCreatedAt();
                     $productdate=explode(' ',$procreateddate);
                     $productcreatedat=$productdate[0];
                     $newproductdate= date("d/m/Y", strtotime($productcreatedat));
                                       
                     $yearlydata=explode("/",$newproductdate);
                     $year=$yearlydata[2];
                     $month=$yearlydata[1];
                     $day=$yearlydata[0];

                     $procalculation = mktime(0,0,0,date($month),date($day),date($year))."</br>";
                                       
                     $subscribedate=$subdate;
                     $yearlydata1=explode("/",$subscribedate);
                     $year1=$yearlydata1[2];
                     $month1=$yearlydata1[1];
                     $day1=$yearlydata1[0];
                     $procalculation1 = mktime(0,0,0,date($month1),date($day1),date($year1))."</br>";
                     
                                        
                     if($procalculation1 <= $procalculation)
                        {
                    ?>
           <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" style="padding:12px 10px 0px;">
                          <?php
                            $Id= $_product->getId();
                            $_myprodsamples = Mage::getModel('downloadable/link')->getCollection()->addProductToFilter($Id);
                            foreach ($_myprodsamples as $_sample){
                                 $video= $_sample['sample_url'];
                                }
                           $vdata=explode("v=",$video);
                            if($vdata['1']!=NULL)
                             {
                                 echo    '<iframe title="YouTube video player" class="youtube-player" type="text/html" width="135" height="135" src="https://www.youtube.com/embed/'.$vdata['1'].'" frameborder="0" allowFullScreen></iframe>';
                             }else {?>
                                  <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                              <?php } ?>
                       </li>
        <?php } endforeach; ?>
    </ol>
 <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
 <?php  else :
 $collection=$this->getCollection();
 $_collectionSize = $collection->count() ?>
  <?php $_columnCount = 3; ?>
  <?php $i=0; foreach ($collection as $_product): ?>
 <?php         
                foreach($membercollection as $memberInfo)
                {
                    $memberId=$memberInfo['member_id'];
                    $subdate=$memberInfo['createddate'];
                    break;
                }
                     $procreateddate=$_product->getCreatedAt();
                     $productdate=explode(' ',$procreateddate);
                     $productcreatedat=$productdate[0];
                     $newproductdate= date("d/m/Y", strtotime($productcreatedat));
                                       
                     $yearlydata=explode("/",$newproductdate);
                     $year=$yearlydata[2];
                     $month=$yearlydata[1];
                     $day=$yearlydata[0];

                     $procalculation = mktime(0,0,0,date($month),date($day),date($year))."</br>";
                                       
                     $subscribedate=$subdate;
                     $yearlydata1=explode("/",$subscribedate);
                     $year1=$yearlydata1[2];
                     $month1=$yearlydata1[1];
                     $day1=$yearlydata1[0];
                     $procalculation1 = mktime(0,0,0,date($month1),date($day1),date($year1))."</br>";
                     $subscribetimestamp=strtotime($subscribedate)."</br>";
                                        
                     if($procalculation1 <= $procalculation)
                        {
               ?>
  <?php if ($i++%$_columnCount==0): ?>
  <ul class="products-grid">
  <?php endif;?>
          <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" style="padding:12px 10px 0px;">
               <?php
                   $Id= $_product->getId();
                   $_myprodsamples = Mage::getModel('downloadable/link')->getCollection()->addProductToFilter($Id);
                   foreach ($_myprodsamples as $_sample){
                          $video= $_sample['sample_url'];
                        }
                  $vdata=explode("v=",$video);
                  if($vdata['1']!=NULL)
                     {
                       echo  '<iframe title="YouTube video player" class="youtube-player" type="text/html" width="135" height="135" src="https://www.youtube.com/embed/'.$vdata['1'].'" frameborder="0" allowFullScreen></iframe>';
                     }else {?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                 <?php } ?>
          </li>
 <?php } if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
 </ul>
 <?php endif ?>
 <?php endforeach ;?>

<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>    
 <?php endif ?>
  <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
 </div>
 