
<?php
 $customer=Mage::getSingleton('customer/session')->getCustomer();
?>
  <form id="merchant-form-validate" method="post" action="<?php echo $this->getUrl()?>register/index/updateinfo/" />
        <div class="fieldset">
            <input type="hidden" value="" name="success_url"/>
            <input type="hidden" value="" name="error_url"/>
            <input type="hidden" value="merchant" name="customer_type"/>
            <h2 class="legend">Edit Personal Information</h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="customer-name">
                         <div class="field name-firstname">
                             <label class="required" for="firstname"><em>*</em>First Name</label>
                                 <div class="input-box">
                                     <input type="text" class="input-text required-entry validate-alpha" title="First Name" value="<?php echo $customer->getFirstname() ;?>" name="firstname" id="firstname">
                                 </div>
                        </div>
                    <div class="field name-lastname">
                        <label class="required" for="lastname"><em>*</em>Last Name</label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry validate-alpha" title="Last Name" value="<?php echo $customer->getLastname() ;?>" name="lastname" id="lastname">
                        </div>
                    </div>
                </div>
                </li>
                
                
                
                <li>
                  <div class="customer-name">
                    <div class="field name-firstname">
                       <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                           <input type="text" name="email" disabled="disabled" id="email_address" value="<?php echo $customer->getEmail() ;?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                        </div>
                    </div>
                      <?php
                      $register_model=Mage::getModel('register/register')->getCollection()->getData();
                      
                      $customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();  
                        /* $resource = Mage::getSingleton('core/resource');
                        $connection= $resource->getConnection('core_read');			
                        $query="select * from tbl_brstcustomer where customer_id = $customer_id";
                        $result=$connection->query($query);
                       * 
                       */
                      foreach($register_model as $customerinfo)
                      { 
                          if($customerinfo['customer_id']==$customer_id) 
                          {
                              break;
                          }
                      }                       
                        ?>
                      
                    <div class="field">
                      <label for="Nick name" class="required">Nick name</label>
                        <div class="input-box">
                            <input type="hidden" class="" title="" value="<?php echo $customerinfo['customer_id'] ;?>" name="custid" id="lastname"/>
                             <input type="text" class="input-text" title="Nick Name" value="<?php echo $customerinfo['nickname'] ;?>" name="nickname" id="lastname">
                        </div>
                    </div>
                </div>
                </li>
              
                <li>
                <div class="">
                       <div class="field">
                        <label class="" for="horse owners">Are you horse owners</label>
                            <input style="margin-left: 10px" type="radio" name="horse_owner" <?php if($customerinfo['horse_owner']=="yes")  echo 'checked="checked"'; ?> value="yes"/>Yes <input type="radio" <?php if($customerinfo['horse_owner']=="no")  echo 'checked="checked"'; ?> value="no" name="horse_owner"/>No
                       </div>
                    <div class="field">
                        <label class="" for="type">They are</label>
                        <input style="margin-left: 10px" type="radio" name="theyare"   <?php if($customerinfo['type']=="Amateur")  echo 'checked="checked"'; ?>  value="Amateur"/>Amateur <input type="radio" name="theyare" <?php if($customerinfo['type']=="Professionals")  echo 'checked="checked"'; ?>  value="Professionals"/>Professionals
                    </div>
                </div>
                </li>
                 <li>
                   <div class="">
                       <div class="field">
                            <label class="required" for="gender">I am</label>
                            <div class="input-box">
                                <select style="width:150px;" name="gender" class="input-text required-entry validate-select">
                                    <option>--Select--</option>
                                    <option value="Male"  <?php if($customerinfo['gender']=='Male'){?> selected="selected" <?php } ?>>Male</option>
                                    <option value="Female" <?php if($customerinfo['gender']=='Female'){?> selected="selected" <?php } ?>>Female</option>
                               </select>
                            </div>
                       </div>
                    <div class="field">
                        <label class="required" for="dob">Date of Birth</label>
                       <div class="input-box">
                           <?php
                                $birtdate=explode('/',$customerinfo['birthdate']);
                                $byear=$birtdate[0];
                                $bmonth=$birtdate[1];
                                $bday=$birtdate[2];
                           //year to start with$birtdate[0];
                                $startdate = 1960;
                          //year to end with - this is set to current year. You can change to specific year
                                $enddate = date("Y");
                                $years = range ($startdate,$enddate);

                                 $startday = 1;
                                $endday = 31;
                                $days = range ($startday,$endday);
                           ?>
                           <select style="width:80px;" name="year" class="input-text required-entry validate-name">
                                <option>--Year--</option>
                                <?php
                                //print years
                                foreach($years as $year)
                                {?>
                                        <option <?php if($year==$byear) { echo "selected='selected'"; } ?> value='<?php echo $year?>'><?php echo $year?></option>
                                <?php }
                                ?>
                             </select>
                             <select style="width:80px;" name="month" class="input-text required-entry validate-name">
                                 <option>--Month--</option>
                                  <option <?php if($bmonth=='1') { echo "selected='selected'"; } ?> value="1" >January</option>
                                   <option <?php if($bmonth=='2') { echo "selected='selected'"; } ?> value="2">February</option>
                                    <option <?php if($bmonth=='3') { echo "selected='selected'"; } ?> value="3">March</option>
                                     <option <?php if($bmonth=='4') { echo "selected='selected'"; } ?> value="4">April</option>
                                      <option <?php if($bmonth=='5') { echo "selected='selected'"; } ?> value="5">May</option>
                                       <option <?php if($bmonth=='6') { echo "selected='selected'"; } ?> value="6">June</option>
                                        <option <?php if($bmonth=='7') { echo "selected='selected'"; } ?> value="7">July</option>
                                         <option <?php if($bmonth=='8') { echo "selected='selected'"; } ?> value="8">August</option>
                                          <option <?php if($bmonth=='9') { echo "selected='selected'"; } ?> value="9">September</option>
                                           <option <?php if($bmonth=='10') { echo "selected='selected'"; } ?> value="10">October</option>
                                            <option <?php if($bmonth=='11') { echo "selected='selected'"; } ?> value="11">November</option>
                                             <option <?php if($bmonth=='12') { echo "selected='selected'"; } ?> value="12">December</option>
                             </select>
                             <select style="width:80px;" name='day' class="input-text required-entry validate-name">
                                   <option>--Day--</option>
                                   <?php
                                        foreach($days as $day)
                                        {?>
                                             <option <?php if($day==$bday) { echo "selected='selected'"; } ?> value='<?php echo $day;?>'><?php echo $day?></option>
                                         <?php }
                                   ?>
                            </select>
                       </div> 
                    </div>
                </div> 
                </li>
              
	</ul>
    </div>
    <input type="hidden" name="keyid" id="keyid" value="<?php echo $customerinfo['id']?>" />
   <div class="buttons-set">
        <button class="button" title="Submit" type="submit" ><span><span>Submit</span></span></button>
  </div>
</form>

