<?php
/**
 * Mageplace Facebook Connect
 *
 * @category    Mageplace_Facebook
 * @package     Mageplace_Facebook_Connect
 * @copyright   Copyright (c) 2011 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */

?>
<div class="page-title">
    <h1><?php echo $this->__('Facebook Connect') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
<?php echo $this->getChildHtml('facebookconnect_form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Facebook Wall') ?></h2>
        <ul class="form-list">
            <li class="control">
            	<input type="checkbox" name="fb_wall_post" id="fb_wall_post" value="1" title="<?php echo $this->__('Post order details to Facebook Wall'); ?>"<?php if($this->getIsPostToFBWall()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            	<label for="fb_wall_post"><?php echo $this->__('Post order details to Facebook Wall') ?></label>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" style="padding:5px;float:right;color:#FFFFFF;background:#333333;width:100px;" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
