<?php 
	$_coreHelper = $this->helper('core');
	$_taxHelper  = $this->helper('tax');
	$numberactive = (int)Mage::getStoreConfig('dailydeal/general/numberactive') ? (int)Mage::getStoreConfig('dailydeal/general/numberactive') : 3;
?>

	<?php 
		$_activedealsCollection = $this->getActivedeals(); 
		$_collectionSize = count($_activedealsCollection);
		if ($_collectionSize > 0){	
			$count=0;
	?>
<div class="block block-deals" >
	<div class="block-title">
		<strong><span><?php echo $this->__('Active deals');?></span></strong>
	</div>
	<div class="block-content">
		<ol id="recently-viewed-items" class="mini-products-list">
		<?php
			
			foreach ($_activedealsCollection as $_activedeal){
					$dealqty = $_activedeal->getDealQty();
			$soldqty = $_activedeal->getSoldQty();
				$_product = Mage::getModel('catalog/product')->load($_activedeal->getProductId());
				
		?>
		<?php if ($count != $numberactive){ ?>		
			<li class="item">
				<a href="<?php echo $_product->getProductUrl() ?>" class="product-image" style="margin-right: 0; width: 60px;" title="<?php echo $_product->getTitle()?>">
					<img src="<?php echo $_product->getImageUrl()?>" width="60px" height="60px"/>
				</a>					
				<div class="product-details" style="margin-left:69px;">
					<p class="product-name" style="margin-top: -5px;">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName()?>">
							<?php echo $_product->getName()?>
						</a>
					</p>
					<div class="price-box" style="margin: 0 0 0 0;">
				    <?php $_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice()) ?>		
					<?php $_finalPrice = $_taxHelper->getPrice($_product, $_product->getFinalPrice()) ?>
					<p class="old-price" style="padding-left:0;">
						<span class="regular-price">
							  <span class="price" style="font-size: 12px;"><?php echo $_coreHelper->currency($_regularPrice,true,false) ?></span>
						</span>
					</p>
					<p class="special-price" style="padding:0;">
		                <span class="price" style="font-size: 12px;">
		                    <?php echo $_coreHelper->currency($_finalPrice,true,false) ?>
		                </span>
	            	</p>	
	            	</div>
	            </div>
	            <div class="clear"></div>
	        	<!-- <div style="padding-left: 0px;font-size: 11px; float: left"> -->
				<div class="dailydeal-qty-box daily-qty-box-active">
						<?php if (($dealqty-$soldqty) > 10){
				
							echo Mage::helper('dailydeal')->__('There are <span class="deal-qty">%s items</span> available.',$dealqty-$soldqty);
							
						} elseif (($dealqty-$soldqty) <= 10 && ($dealqty-$soldqty) > 1) {
						
							echo Mage::helper('dailydeal')->__('Hurry, there are only <span class="deal-qty">%s items</span> left!',$dealqty-$soldqty);
					
						}elseif (($dealqty-$soldqty) == 1){
							echo Mage::helper('dailydeal')->__('Hurry, there is only <span class="deal-qty">%s item</span> left!',$dealqty-$soldqty);
						}?>
				</div>
			</li>
		<?php $count++;?>
	<?php }?>
<?php }?>
		</ol>
		<script type="text/javascript">decorateList('recently-viewed-items');</script>
		<div class="actions">
			<a style="float: right;" href="<?php echo $this->getUrl(Mage::helper('dailydeal')->getRewriteUrl('dailydeal/index')); ?>"><?php echo Mage::helper('dailydeal')->__('View all');?></a>
			
		</div>
		</div>
</div>
<?php }?>

