<?php 
	$_coreHelper = $this->helper('core');
	$_taxHelper  = $this->helper('tax');
	$numberactive = (int)Mage::getStoreConfig('dailydeal/general/numberactive') ? (int)Mage::getStoreConfig('dailydeal/general/numberactive') : 3;
	$title = Mage::getStoreConfig('dailydeal/general/title');
	$timechange = (int)Mage::getStoreConfig('dailydeal/general/timechange'); 
?>
<?php 	
	$arraydays = $this->getWeeklydeal();	
?>
<!--  anh san pham, ten san pham, gia cu, gia khuyen mai -->
<!--Chu y la load 2 lan file open.js se gay ra xung dot-->
<script type="text/javascript" src="<?php echo $this->getSkinUrl('mw_dailydeal/js/tooltip/opentip.js')?>">
//this.list.findAll(function(t) {return (t.options.group == groupName);}).invoke('doHide');
</script>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('mw_dailydeal/css/calendar.css')?>" type="text/css" media="all"/>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('mw_dailydeal/css/tooltip/opentip.css')?>" type="text/css" media="all"/>

<script type="text/javascript">
	var anonymous = [];
	function hiddendeals(){
		for (k = 0; k< 7; k++){
			var idAno = document.getElementById('anonymous_element_'+k); 
			if (idAno != null){
		//		Dung de remove luon id, de cho bo nho dem cua trang web ko chua qua n tag
		//		document.body.removeChild(idAno);
		//		Doi attibute cua 1 tag
				idAno.removeClassName('ot-completely-visible').addClassName('ot-completely-hidden');
			 } else continue;  			
		}
	}
</script>
<div id="blockcalendar" class="block block-deals" style="border: 1px solid;" >
	<h1><?php echo $this->__('Deals of Week')?></h1>
	<table class="doctable table"  >
		<tbody class="tbody">
		<tr>
			<?php 
				$temp = array();		
				$i = 0;
				$j = 0;
				$m = date('m',Mage::getModel('core/date')->timestamp(time()));
				$d = date('d',Mage::getModel('core/date')->timestamp(time()));
				$Y = date('Y',Mage::getModel('core/date')->timestamp(time()));
				while ($i<4){
					$tomorrowshow = date('d-m',mktime(0,0,0,$m,$d+$i,$Y));
					$textual = date('D',mktime(0,0,0,$m,$d+$i,$Y));
					$tomorrow = date('Y-m-d',mktime(0,0,0,$m,$d+$i,$Y));
			?>
			
			<?php if (in_array($tomorrow,$arraydays)){ $temp[$j] = $i;$j++;}?>
	
					
			<td style="<?php if (in_array($tomorrow,$arraydays)) {
									echo 'background-color: #A7F1F4; font-weight: bold; border: 2px solid white; ';
								}else { 
									echo 'color: grey; border: 2px solid white; ';}?>" 
				<?php if (in_array($tomorrow,$arraydays)) echo 'class="select_deal"';?>
				>
			<span id="cell-<?php echo $i;?>" ><?php echo $tomorrowshow.' '.$textual;?></span></td>
		
			<?php 
				$i++;
				}
			?>
	
		</tr>
		<tr>
			<?php 			
				while ($i<7){
					$tomorrowshow = date('d-m',mktime(0,0,0,date('m'),date('d')+$i,date("Y")));
					$textual = date('D',mktime(0,0,0,date('m'),date('d')+$i,date("Y")));
					$tomorrow = date('Y-m-d',mktime(0,0,0,$m,$d+$i,$Y));
			?>
		<?php if (in_array($tomorrow,$arraydays)){ $temp[$j] = $i;$j++;}?>
			<td id="<?php echo $i;?>" style="<?php if (in_array($tomorrow,$arraydays)) {echo 'background-color: #A7F1F4; font-weight: bold; border: 2px solid white; ';} else { echo 'color: grey; border: 2px solid white; ';}?>" 
				<?php if (in_array($tomorrow,$arraydays)) echo 'class="select_deal"'?>
				>
						<span id="cell-<?php echo $i;?>" ><?php echo $tomorrowshow.' '.$textual;?></span></td>			
			<?php 
				$i++;
				}
			?>	
			<td id="cell_more" style="border: 2px solid white; ">
			<a style="float: right; text-align: center;" href="<?php ;echo $this->getUrl(Mage::helper('dailydeal')->getRewriteUrl('dailydeal/index')); ?>"><?php echo Mage::helper('dailydeal')->__('More'); ?></a>
			</td>
		</tr>
		</tbody>
	</table>

</div>
	
<script type="text/javascript">
<?php 	
	for ($k = 0; $k < count($temp); $k++){
		$daybycell =  date('Y-m-d',mktime(0,0,0,$m,$d+$temp[$k],$Y));
?>
		listminicart('<?php echo $temp[$k];?>','<?php echo $daybycell?>');
<?php }?>

	//hideOn: 'click', an di roi moi cho show deal dc, 
	//neu dung su kien window.onclick thi bi xung dot voi su kien nay
	Opentip.styles.grouped = {
			stem: false,
			target: true,
			tipJoint: ['center', 'top'],
			hideTrigger: ['closeButton','trigger'],
//			showOn: 'mouseover',
			hideOn: 'click',			
			group: 'myGroudfp'
		}
		
</script>
