<a name="simple-forum-top"></a>
<?php echo $this->getHeadHtml(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getBreadCrumbs(); ?>
<?php echo $this->getTop(); ?>
<div style="background:url('http://54.228.195.42/magento/skin/frontend/default/videoplatform/forum/images/topic-lists-from2.png') no-repeat;padding:25px;">
<div class="forum-top" style="border-bottom:1px solid #CECECE;">
<table width="100%">
	<tr>
		<td>
			<div class="forum-title" style="width:300px;float:left;border:none;">
				<?php echo $this->getTitleContent(); ?>
			</div>
		
			<div class="forum-controls" style="width:320px;float:right;margin:5px 0 5px">
				<?php echo $this->getControls(); ?>
			</div>
		
	</tr>
</table>
</div>
    <div class="toptoolbar" style="width:930px;">
<?php echo $this->getToolbarHtml(); ?>
    </div>
<?php $posts = $this->getAllObjects(); 

?>

<div class="forumpost">
    <table witdh="100%" border="0" id="forum_table_posts" class="data-table">
		<thead style="background:#333333;">
		<tr class="first last">
			<th class="forum-th" width="15%"><?php echo $this->__('Member') ?></th>			
			<th  class="forum-th"width="75%"><?php echo $this->__('Post') ?></th>
		<tr>
		</thead>
	<?php if($posts->getSize()): ?>
	<?php $all_posts = $posts->getSize(); ?>
		<?php foreach($posts as $post):
              // echo "<pre>";print_r($post);die('helop');  ?>
		<tr>
			<td valign="top" class="forum-post-left">
                            <?php 
                            $avatar = Mage::getModel('userprofile/avatars')->setStoreData(1)->loadByCustomerId($post[system_user_id]);
                            if($avatar!=NULL)
                            {
                                if($avatar->getValue()!=NULL){ $ava_src = str_replace('index.php','',$this->getBaseUrl()).'media/userprofile/avatar/'.$post[system_user_id].'/'.$avatar->getValue();}
                                else{$ava_src = str_replace('index.php','',$this->getBaseUrl()).'media/userprofile/avatar/dummy/dummy.jpg';        
                                }
                            }
                            else
                            {
                            $ava_src = str_replace('index.php','',$this->getBaseUrl()).'media/userprofile/avatar/dummy/dummy.jpg'; 
                            }
                           ?>
                            <div style="margin-bottom:7px;">
                              <img src="<?php echo $ava_src;?>" height="125" width="125" alt="" />
                            </div>
				<h5 class="simple-forum-h-created" style="font-weight:normal" id="<?php echo $this->getReplyIdBegin() ?><?php echo $post->getId() ?>"><?php echo $this->__('Posted By'); ?>: <?php echo $this->getUser_name_post($post); ?>
				</h5>
				<div class="simple-forum-user-total-posts"><?php echo $this->__('Anzahl Beiträge') ?>: <?php echo $post->getUserTotalPosts() ?></div>
				<div class="simple-forum-user-joined-date"><?php echo $this->__('Mitgleid seit') ?>: <?php echo $this->getFormatedDate($post->getUserJoined()); ?></div>

			</td>						
			<td valign="top" class="forum-post-right" id="<?php echo $this->getReplyIdBegin() ?><?php echo $post->getId() ?>-td">
				</h5>
				<?php echo $post->getPost(); ?>
			<div class="forum-post-signature">
				<dl class="forum-post-signature-posted">
					<table width="100%" id="forum-post-bottom">
						<tr>
							<td width="50%">
								<b>
									<?php echo $this->__('Posted'); ?>
								</b>:
								<?php echo $this->getFormatedDate($post->getCreated_time()); ?>
							</td>
							<td width="50%" align="right">
							<div class="forum-controls-user">
							<nobr>
							<a style="text-decoration:none !important;" href="#simple-forum-top">
								<img src="<?php echo $this->getSkinUrl('forum/images/arrowimg.png') ?>" alt="<?php echo $this->__('Top') ?>" title="<?php echo $this->__('Top') ?>" border="0" />
                                                                <span style="color:#333333">
                                                                    TOP
                                                                </span>
 							</a>
								<?php if($this->getHaveEditableRights($post->getSystem_user_id())): ?>
									
										<a href="<?php echo $this->getEditPostUrl($post->getId(), $post); ?>"><img src="<?php echo $this->getSkinUrl('forum/images/page_edit.png') ?>" alt="<?php echo $this->__('Edit') ?>" title="<?php echo $this->__('Edit') ?>" border="0" /></a>&nbsp;
<a href="<?php echo $this->getDeletePostUrl($post->getId()); ?>" onclick="if(confirm('<?php echo $this->__('Are You sure?') ?>')) document.location.href=this.href; return false;"><img src="<?php echo $this->getSkinUrl('forum/images/delete.png') ?>" alt="<?php echo $this->__('Delete') ?>" title="<?php echo $this->__('Delete') ?>" border="0" /></a>
									<?php if($this->isModerator()): ?>
										<?php if($post->getStatus() == 1): ?>
											&nbsp;<a href="<?php echo $this->getDeactivatePostUrl($post->getId()); ?>" ><img src="<?php echo $this->getSkinUrl('forum/images/cancel.png') ?>" border="0" alt="<?php echo $this->__('Deactivate') ?>" title="<?php echo $this->__('Deactivate') ?>" /></a>
										<?php elseif($post->getStatus() == 0): ?>
											&nbsp;<a href="<?php echo $this->getActivatePostUrl($post->getId()); ?>" ><img src="<?php echo $this->getSkinUrl('forum/images/add.png') ?>" alt="<?php echo $this->__('Activate') ?>" title="<?php echo $this->__('Activate') ?>" border="0" /></a>
										<?php endif; ?>
									<?php endif; ?>
									
									
								<?php endif; ?>
							</nobr>
							</div>
							</td>
						</tr>
					</table>
				</dl>
			</div>
			</td>
		</tr>
		<?php endforeach; ?>

	<?php else: ?>
		<tr>
		<td colspan="4">
			<div style="text-align:center">
				<?php echo $this->__('No Data To Display'); ?>
			</div>
		</td>
	<?php endif;?>
	</table>
	<?php echo $this->getToolbarHtml(); ?>
	<br>
	
<table width="100%">
	<tr>
		<td>
			<div class="forum-title" style="width:300px;float:left;border:none;">
				 <?php echo $this->getPagerHtml() ?>
			</div>
		
			<div class="forum-controls" style="width:320px;float:right;margin:5px 0 5px">
				<?php echo $this->getControls(); ?>
			</div>
		
	</tr>
</table>

<?php if($this->getAllowFastReply()): ?>
<div id="simple-forum-fast-reply-block">
	<form id="simple-forum-fast-replay-form" action="<?php echo $this->getSaveUrl() ?>" method="post">
		    <input type="hidden" name="topic_id" value="<?php echo $this->getTopicId() ?>" >
		    <input type="hidden" name="back" value="<?php echo $this->getBackFormUrl() ?>" />
		    <input type="hidden" name="parent_id" value="<?php echo $this->getParentId() ?>" />
		    <br>
			<textarea name="Post" id="simple-forum-fast-reply-textarea" ></textarea>
			<div>
				<ul class="form-list">
					<?php echo $this->getRecaptchField() ?>
				</ul>
			</div>
			<div id="simple-forum-fast-reply-button-block">
				<button class="simple-forum-default-button" onclick="forumFastReplaySF(); return false;" title="<?php echo $this->__('Cancel'); ?>" ><?php echo $this->__('Cancel'); ?></button>
				<button class="simple-forum-default-button" type="submit" title="<?php echo $this->__('Submit Post'); ?>" ><?php echo $this->__('Submit Post'); ?></button>
			</div>
	</form>
</div>
<?php endif; ?>
</div>
</div>