<?php
    $data = $this->getRequest()->getServer('HTTP_REFERER');
    $customer = Mage::getModel('customer/session')->getCustomer();
    $customerId = $customer->getId();
    $campaign = Mage::registry('current_campaign');
    $campaignId = $campaign->getId();
    $affiliate = Mage::registry('current_affiliate');
    $affiliateId = $affiliate->getId();
?>
    <script type="text/javascript">
        function submitembedcode() {
            jQuery("#user-form-loader").show();
            jQuery('#showdiv').text("");
            var chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghijklmnopqrstuvwxyz";

            /* var embedcode;
             var pos;
             pos = Math.floor(Math.random() * chars.length);
             embedcode=(chars.substr(pos,5));*/
            var iteration = 0;
            var embedcode = "";
            var randomNumber;
            if (special == undefined) {
                var special = false;
            }
            while (iteration < 5) {
                randomNumber = (Math.floor((Math.random() * 100)) % 94) + 33;
                if (!special) {
                    if ((randomNumber >= 33) && (randomNumber <= 47)) {
                        continue;
                    }
                    if ((randomNumber >= 58) && (randomNumber <= 64)) {
                        continue;
                    }
                    if ((randomNumber >= 91) && (randomNumber <= 96)) {
                        continue;
                    }
                    if ((randomNumber >= 123) && (randomNumber <= 126)) {
                        continue;
                    }
                }
                iteration++;
                embedcode += String.fromCharCode(randomNumber);
            }

            jQuery('#embed_code').val(embedcode);

            jQuery.ajax({
                url: '<?php echo Mage::getUrl('affiliate/customer_affiliate/embedcode') ?>',
                type: 'POST',
                dataType: 'json',
                data: jQuery('#affiliate-products-form').serialize(),
                success: function (data) {
                    if (data.success == 'success') {
                        if (jQuery('#showdiv').css('display') == 'none') {
                            jQuery('#showdiv').show();
                        }
                        jQuery("#user-form-loader").hide();

                        var showiframe = '<iframe frameborder="0" width="1060" height="500"  src="<?php echo Mage::getUrl('') ?>embeded/' + embedcode + '" name="embedcode" id="embedcode"></iframe>';
                        jQuery('#showdiv').text("");
                        jQuery('html,body').animate({scrollTop: jQuery("#showdiv").offset().top}, 1000);
                        jQuery('#showdiv').html(showiframe);
                    }
                }
            });
        }
    </script>
   <?php   //if($data!='http://54.228.195.42/magento/affiliate/customer_affiliate/view/status/1/' )  { ?>
 <div class="campaings fieldset">
     <div class="affialiatetitle">
         <h2 class=""><?php echo $this->__("All Products"); ?>
             <div style="height: 30px;float:right;width:100px;">
                 <button style="background:#333333;padding:5px;color:#FFFFFF;float:right;" id="embedcode" type="button"
                         class="button" name="embedcode" style="float:right;margin-bottom:10px;"
                         title="<?php echo $this->__("Embed Code"); ?>" onClick="submitembedcode()">
                     <span><span style="float:right;"><?php echo $this->__("Embed Code"); ?></span></span>
                 </button>
             </div>
         </h2>
     </div>
     <div>
         <form id="affiliate-products-form">
             <input type="hidden" value="<?php echo Mage::getBaseUrl(); ?>" id="defaulturl"/>
             <input type="hidden" value="<?php echo $customerId; ?>" name="custid"/>
             <input type="hidden" value="<?php echo $affiliateId; ?>" name="affiliate_Id"/>
             <input type="hidden" value="<?php echo $campaignId; ?>" name="campaign_Id"/>
             <input type="hidden" name="embed_code" id="embed_code"/>

             <script type="text/javascript">
                 jQuery(document).ready(function () {
                     jQuery(".productname_video").css({ top: '-59px' });
                     jQuery(".productname_video").css("width", "220")
                 });
             </script>

             <?php echo $this->getChildHtml('affiliate-products-lists') ?>

         </form>
     </div>
     <div id="user-form-loader" style="display:none; margin-right: 5px; margin-top: -65px;float:right;"><img
             style="height: 65px;" src="<?php echo $this->getSkinUrl() ?>images/loadingr.gif"/></div>
     <div style="height: 30px;">
         <button style="background:#333333;padding:5px;color:#FFFFFF;float:right;" id="embedcode" type="button"
                 class="button" name="embedcode" style="float:right;margin-bottom:10px;"
                 title="<?php echo $this->__("Embed Code"); ?>" onClick="submitembedcode(); return false;">
             <span><span style="float:right;"><?php echo $this->__("Embed Code"); ?></span></span>
         </button>
     </div>

 </div>
 <div style="text-align:center;">
     <textarea id="showdiv" style="width:500px;height:75px;"> </textarea>
 </div>
    <?php //} ?>