<?php 
	$_coreHelper = $this->helper('core');
	$_taxHelper  = $this->helper('tax');
	$title = Mage::getStoreConfig('dailydeal/general/title');
?>

<?php 		
	$_dealCollection = $this->getDeals(); 
	$_collectionSize = count($_dealCollection);
	if ($_collectionSize > 0){
		foreach ($_dealCollection as $_deal){
?>
		<?php 
			$dealqty = $_deal->getDealQty();
			$soldqty = $_deal->getSoldQty();
			$gmtcore = Mage::getSingleton('core/date')->getGmtOffset();
			
			$beforetime = Mage::getModel('core/date')->timestamp(time())-strtotime($_deal->getStartDateTime());
			$aftertime = strtotime($_deal->getEndDateTime())- Mage::getModel('core/date')->timestamp(time());
			if ($dealqty > $soldqty && ($aftertime > 0) && ($beforetime >= 0)){
			$_product = Mage::getModel('catalog/product')->load($_deal->getProductId());		
				
		?>
		<div class="block block-todaydeal" >
			<div class="title">
				<?php if ($title == ''){?>
			<h3 style="color: white;padding-top:5px "><?php echo $this->__('Get it before it&acute;s gone!');?></h3>
			<?php }else {?>
			<h3 style="color: white;padding-top:5px "><?php echo $title;?></h3>
			<?php }?>
			</div>
			<div class="block-content">
				<ol  class="mini-products-list">
					<li>
						<p class="product-name">
							<a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName()?>">
								<?php echo $_product->getName()?>
							</a>
						</p>
						<div class="product">
							<a class="product-image" title="<?php echo $_product->getTitle()?>" href="<?php echo $_product->getProductUrl() ?>">
							<img src="<?php echo $_product->getImageUrl()?>" width="70px" alt="<?php echo $_product->getTitle()?>" /></a>		
						</div>
						<div class="product-details">
							<?php $_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice()) ?>
							<?php $_finalPrice = $_taxHelper->getPrice($_product, $_product->getFinalPrice()) ?>
							<p class="old-price" >
								<span class="regular-price">
									  <span class="price"><?php echo $_coreHelper->currency($_regularPrice,true,false) ?></span>
								</span>
							</p>
							<p class="special-price">
								<span class="price">
									<?php echo $_coreHelper->currency($_finalPrice,true,false) ?>
								</span>
							</p>	
							<?php 
								$dealqty = $_deal->getDealQty();
								$soldqty = $_deal->getSoldQty();
							?>
							<div class="dailydeal-qty-box">
							<?php if (($dealqty-$soldqty) > 10){
				
								echo Mage::helper('dailydeal')->__('There are <span class="deal-qty">%s items</span> available.',$dealqty-$soldqty);
					
								} elseif (($dealqty-$soldqty) <= 10 && ($dealqty-$soldqty) > 1) {
								
									echo Mage::helper('dailydeal')->__('Hurry, there are only <span class="deal-qty">%s items</span> left!',$dealqty-$soldqty);
							
								}elseif (($dealqty-$soldqty) == 1){
									echo Mage::helper('dailydeal')->__('Hurry, there is only <span class="deal-qty">%s item</span> left!',$dealqty-$soldqty);
								}
							?>
							</div>
						</div>
					</li>
				</ol>
				<!-- Countdown Javascript -->
				<div id="counter" class="counter">
					<ul class="countdown">	
						 <li class="first"><div class="countdown_num" id="cd_hour-<?php echo $_deal->getDailydealId()?>"></div><div id="cd_hour">Hours</div></li>
						<li><div class="countdown_num" id="cd_min-<?php echo  $_deal->getDailydealId()?>"></div><div id="cd_minute">Minutes</div></li>
						<li class="last"><div class="countdown_num" id="cd_sec-<?php echo  $_deal->getDailydealId()?>"></div><div id="cd_second">Seconds</div></li>
					</ul>
					<div class="clear"><span>&nbsp;</span></div>
				</div>
				<div id="expired" style="display:none;">
					<?php echo Mage::helper('dailydeal')->__('The deadline has passed.'); ?>
				</div>
			</div>
		</div>

		<script type="text/javascript">
		
			function addLoadEvent(func) {
			  var oldonload = window.onload;
			  if (typeof window.onload != 'function') {
			    window.onload = func;
			  } else {
			    window.onload = function() {
			      if (oldonload) {
			        oldonload();
			      }
			      func();
			    }
			  }
			}
			
			addLoadEvent(function() {
				 countDown(<?php echo date('Y',strtotime($_deal->getEndDateTime()));?>, 
							<?php echo date('m',strtotime($_deal->getEndDateTime()));?>, 
							<?php echo date('d',strtotime($_deal->getEndDateTime()));?>,
						  	<?php echo date('H',strtotime($_deal->getEndDateTime()));?>,
							<?php echo date('i',strtotime($_deal->getEndDateTime()));?>,
							  "cd_hour-<?php echo $_deal->getDailydealId()?>",
							  "cd_min-<?php echo  $_deal->getDailydealId()?>",
							  "cd_sec-<?php echo  $_deal->getDailydealId()?>");
			});
		</script>     
		<?php break;?>
	<?php } ?>
	<?php } ?>
	<?php } ?>

